// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/IbadT/business_bank_back",
            "email": "support@matematika.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/generate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Генерирует финансовую выписку с транзакциями на основе переданных параметров. Поддерживает модели B2C и B2B, позволяет задавать желаемый процент прибыли, начальный баланс и дополнительные кастомные данные.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statements"
                ],
                "summary": "Генерация финансовой выписки",
                "parameters": [
                    {
                        "description": "Параметры генерации выписки",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная генерация выписки",
                        "schema": {
                            "$ref": "#/definitions/dto.GenerateResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос - ошибки валидации входных параметров",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Требуется авторизация",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "422": {
                        "description": "Ошибка валидации - транзакция приведет к отрицательному балансу",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/holidays": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Получает список всех праздников для указанного года. Формат года: YYYY (например, 2024). Требуется авторизация.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holidays"
                ],
                "summary": "Получить список всех праздников для указанного года",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Год для получения праздников в формате YYYY",
                        "name": "year",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение списка праздников",
                        "schema": {
                            "$ref": "#/definitions/dto.GetHolidaysResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос - ошибки валидации входных параметров",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Требуется авторизация",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Добавляет новый праздник в базу данных. Требуется авторизация. Поддерживаемые страны: RU, US.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holidays"
                ],
                "summary": "Добавление праздника",
                "parameters": [
                    {
                        "description": "Данные для добавления праздника",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.HolidayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное добавление праздника",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос - ошибки валидации входных параметров",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Требуется авторизация",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/holidays/is-holiday": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Проверяет, является ли указанная дата праздником. Формат даты: YYYY-MM-DD (например, 2024-12-15). Требуется авторизация.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holidays"
                ],
                "summary": "Проверка является ли дата праздником",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Дата для проверки в формате YYYY-MM-DD",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Результат проверки даты",
                        "schema": {
                            "$ref": "#/definitions/dto.IsHolidayResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос - ошибки валидации входных параметров",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Требуется авторизация",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/holidays/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет существующий праздник в базе данных по его ID. Требуется авторизация.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holidays"
                ],
                "summary": "Обновление праздника",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID праздника",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления праздника",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.HolidayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление праздника",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос - ошибки валидации входных параметров",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Требуется авторизация",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Праздник не найден",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет праздник из базы данных по его ID. Требуется авторизация.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holidays"
                ],
                "summary": "Удаление праздника",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID праздника",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное удаление праздника",
                        "schema": {
                            "$ref": "#/definitions/dto.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос - ошибки валидации входных параметров",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Требуется авторизация",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Праздник не найден",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "description": "Авторизует пользователя по email и паролю. Возвращает токены доступа и обновления.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Авторизация пользователя",
                "parameters": [
                    {
                        "description": "Данные для авторизации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная авторизация",
                        "schema": {
                            "$ref": "#/definitions/dto.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос - ошибки валидации входных параметров",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Неверный email или пароль",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/register": {
            "post": {
                "description": "Регистрирует нового пользователя по email и паролю. Возвращает токены доступа и обновления.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная регистрация",
                        "schema": {
                            "$ref": "#/definitions/dto.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный запрос - ошибки валидации входных параметров",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Пользователь с таким email уже существует",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CompanyInfo": {
            "description": "Информация о владельце и названии компании",
            "type": "object",
            "properties": {
                "companyName": {
                    "type": "string",
                    "example": "ООО \"Пример\""
                },
                "ownerName": {
                    "type": "string",
                    "example": "Иван Иванов"
                }
            }
        },
        "dto.CustomContractor": {
            "description": "Кастомный контрагент с указанием типа транзакций",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "ООО \"Партнер\""
                },
                "transactionType": {
                    "type": "string",
                    "example": "income"
                }
            }
        },
        "dto.CustomData": {
            "description": "Дополнительные данные для кастомизации генерации: ручные транзакции, информация о компании, кастомные клиенты и контрагенты",
            "type": "object",
            "properties": {
                "companyInfo": {
                    "$ref": "#/definitions/dto.CompanyInfo"
                },
                "customContractors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CustomContractor"
                    }
                },
                "customCustomers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "manualTransactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ManualTransaction"
                    }
                }
            }
        },
        "dto.DailyBalance": {
            "description": "Баланс счета на конец дня",
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number",
                    "example": 65000
                },
                "date": {
                    "type": "string",
                    "example": "2024-12-15"
                }
            }
        },
        "dto.FinancialSummary": {
            "description": "Сводная информация о финансах за период",
            "type": "object",
            "properties": {
                "finalBalance": {
                    "type": "number",
                    "example": 150000
                },
                "initialBalance": {
                    "type": "number",
                    "example": 50000
                },
                "netProfit": {
                    "type": "number",
                    "example": 100000
                },
                "totalExpenses": {
                    "type": "number",
                    "example": 1100000
                },
                "totalRevenue": {
                    "type": "number",
                    "example": 1200000
                }
            }
        },
        "dto.ForwardingInfo": {
            "description": "Дополнительная информация о компании и контрагентах",
            "type": "object",
            "properties": {
                "associatedCard": {
                    "type": "string",
                    "example": "****1234"
                },
                "companyName": {
                    "type": "string",
                    "example": "ООО \"Пример\""
                },
                "customContractors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CustomContractor"
                    }
                },
                "customCustomers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ownerName": {
                    "type": "string",
                    "example": "Иван Иванов"
                }
            }
        },
        "dto.GenerateRequest": {
            "description": "Параметры для генерации финансовой выписки",
            "type": "object",
            "required": [
                "desiredProfitPercent",
                "initialBalance",
                "model",
                "month",
                "turnover",
                "year"
            ],
            "properties": {
                "customData": {
                    "$ref": "#/definitions/dto.CustomData"
                },
                "desiredProfitPercent": {
                    "type": "number",
                    "maximum": 100,
                    "minimum": 0,
                    "example": 10
                },
                "initialBalance": {
                    "type": "number",
                    "minimum": 0,
                    "example": 300000
                },
                "model": {
                    "type": "string",
                    "enum": [
                        "B2C",
                        "B2B"
                    ],
                    "example": "B2C"
                },
                "month": {
                    "type": "integer",
                    "maximum": 12,
                    "minimum": 1,
                    "example": 12
                },
                "scaleFactor": {
                    "type": "integer",
                    "maximum": 10,
                    "minimum": 1,
                    "example": 1
                },
                "turnover": {
                    "type": "number",
                    "minimum": 0,
                    "example": 100000
                },
                "year": {
                    "type": "integer",
                    "maximum": 2100,
                    "minimum": 2000,
                    "example": 2024
                }
            }
        },
        "dto.GenerateResponse": {
            "description": "Ответ с сгенерированными транзакциями и финансовой сводкой",
            "type": "object",
            "properties": {
                "dailyClosingBalances": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DailyBalance"
                    }
                },
                "financialSummary": {
                    "$ref": "#/definitions/dto.FinancialSummary"
                },
                "forwardingInfo": {
                    "$ref": "#/definitions/dto.ForwardingInfo"
                },
                "transactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Transaction"
                    }
                }
            }
        },
        "dto.GetHolidaysResponse": {
            "description": "Список праздников за указанный год",
            "type": "object",
            "properties": {
                "holidays": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.HolidayResponse"
                    }
                },
                "year": {
                    "type": "string",
                    "example": "2024"
                }
            }
        },
        "dto.HolidayRequest": {
            "description": "Данные для добавления праздника в базу данных. Дата в формате YYYY-MM-DD (например, 2025-12-25).",
            "type": "object",
            "required": [
                "country",
                "holidayDate",
                "name"
            ],
            "properties": {
                "country": {
                    "type": "string",
                    "example": "RU"
                },
                "holidayDate": {
                    "description": "Формат: YYYY-MM-DD",
                    "type": "string",
                    "example": "2025-12-25"
                },
                "name": {
                    "type": "string",
                    "example": "Новый Год"
                }
            }
        },
        "dto.HolidayResponse": {
            "description": "Информация о празднике",
            "type": "object",
            "properties": {
                "country": {
                    "type": "string",
                    "example": "RU"
                },
                "holidayDate": {
                    "type": "string",
                    "example": "2024-12-15"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "type": "string",
                    "example": "Новый Год"
                }
            }
        },
        "dto.IsHolidayResponse": {
            "description": "Результат проверки, является ли дата праздником",
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2024-12-15"
                },
                "isHoliday": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "dto.LoginRequest": {
            "description": "Параметры для авторизации пользователя",
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "password123"
                }
            }
        },
        "dto.ManualTransaction": {
            "description": "Транзакция, добавленная вручную пользователем",
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 15000
                },
                "category": {
                    "type": "string",
                    "example": "Sales"
                },
                "method": {
                    "type": "string",
                    "example": "card"
                },
                "transactionDate": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2024-12-15T10:30:00Z"
                },
                "type": {
                    "type": "string",
                    "example": "income"
                }
            }
        },
        "dto.MessageResponse": {
            "description": "Стандартный ответ с сообщением об успешной операции",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "message": {
                    "type": "string",
                    "example": "Operation completed successfully"
                }
            }
        },
        "dto.RegisterRequest": {
            "description": "Параметры для регистрации пользователя",
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "password123"
                }
            }
        },
        "dto.TokenResponse": {
            "description": "Ответ с токенами доступа и обновления после успешной авторизации",
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "dto.Transaction": {
            "description": "Информация об одной транзакции",
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 15000
                },
                "balanceAfter": {
                    "type": "number",
                    "example": 65000
                },
                "calculationDetails": {
                    "type": "object",
                    "additionalProperties": true
                },
                "category": {
                    "type": "string",
                    "example": "Sales"
                },
                "isManual": {
                    "type": "boolean",
                    "example": false
                },
                "method": {
                    "type": "string",
                    "example": "card"
                },
                "postingDate": {
                    "type": "string",
                    "example": "2024-12-15"
                },
                "transactionDate": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2024-12-15T10:30:00Z"
                },
                "transactionId": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "type": {
                    "type": "string",
                    "example": "income"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Введите только токен (без Bearer). Получите токен через /api/login или /api/register. Swagger автоматически добавит префикс \"Bearer \"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "API для генерации финансовых выписок",
            "name": "statements"
        },
        {
            "description": "API для аутентификации и регистрации пользователей",
            "name": "auth"
        },
        {
            "description": "API для управления праздниками",
            "name": "holidays"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Matematika API",
	Description:      "API для генерации финансовых выписок и транзакций. Сервис позволяет генерировать реалистичные финансовые выписки на основе заданных параметров (оборот, желаемая прибыль, модель бизнеса).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
