syntax = "proto3";

package holiday;

import "validate/validate.proto";

option go_package = "github.com/IbadT/business_bank_back/pkg/proto";

service HolidayService {
    rpc AddHoliday(AddHolidayRequest) returns (AddHolidayResponse);
    rpc GetHolidays(GetHolidaysRequest) returns (GetHolidaysResponse);
    rpc CheckIsHoliday(CheckIsHolidayRequest) returns (CheckIsHolidayResponse);
    rpc UpdateHoliday(UpdateHolidayRequest) returns (UpdateHolidayResponse);
    rpc DeleteHoliday(DeleteHolidayRequest) returns (DeleteHolidayResponse);
}

message Holiday {
    string id = 1 [(validate.rules).string = {uuid: true, ignore_empty: true}]; // UUID for update/delete, empty for create
    string holiday_date = 2 [(validate.rules).string = {min_len: 1, pattern: "^\\d{4}-\\d{2}-\\d{2}$"}]; // YYYY-MM-DD format
    string name = 3 [(validate.rules).string = {min_len: 1}];
    string country = 4 [(validate.rules).string = {in: ["RU", "US"]}];
}

message AddHolidayRequest {
    Holiday holiday = 1 [(validate.rules).message = {required: true}];
}

message AddHolidayResponse {
    string message = 1;
    int32 code = 2;
}

message GetHolidaysRequest {
    string year = 1 [(validate.rules).string = {min_len: 1, pattern: "^\\d{4}$"}]; // YYYY format
}

message GetHolidaysResponse {
    repeated Holiday holidays = 1;
    string year = 2;
}

message CheckIsHolidayRequest {
    string date = 1 [(validate.rules).string = {min_len: 1, pattern: "^\\d{4}-\\d{2}-\\d{2}$"}]; // YYYY-MM-DD format
}

message CheckIsHolidayResponse {
    bool is_holiday = 1;
    string date = 2;
}

message UpdateHolidayRequest {
    Holiday holiday = 1 [(validate.rules).message = {required: true}];
}

message UpdateHolidayResponse {
    string message = 1;
    int32 code = 2;
}

message DeleteHolidayRequest {
    string id = 1 [(validate.rules).string = {uuid: true, min_len: 1}];
}

message DeleteHolidayResponse {
    string message = 1;
    int32 code = 2; 
}
