syntax = "proto3";

package transaction;

import "common.proto";
import "validate/validate.proto";

option go_package = "github.com/IbadT/business_bank_back/pkg/proto";

service TransactionService {
    rpc CreateTransaction(CreateTransactionRequest) returns (CreateTransactionResponse);
    rpc CreateBatchTransactions(CreateBatchTransactionsRequest) returns (CreateBatchTransactionsResponse);
    rpc GetTransactionsCount(GetTransactionsCountRequest) returns (GetTransactionsCountResponse);
    rpc GetTransactionsByTypeAndRequestID(GetTransactionsByTypeAndRequestIDRequest) returns (GetTransactionsByTypeAndRequestIDResponse);
    rpc GetTransactionsByMethodAndRequestID(GetTransactionsByMethodAndRequestIDRequest) returns (GetTransactionsByMethodAndRequestIDResponse);
    rpc GetTransactionsByRequestID(GetTransactionsByRequestIDRequest) returns (GetTransactionsByRequestIDResponse);
}

message CreateTransactionRequest {
    string request_id = 1 [(validate.rules).string = {uuid: true, min_len: 1}];
    string transaction_date = 2 [(validate.rules).string = {min_len: 1}]; // ISO8601 format
    string posting_date = 3 [(validate.rules).string = {ignore_empty: true, pattern: "^\\d{4}-\\d{2}-\\d{2}$"}]; // YYYY-MM-DD format, optional
    string type = 4 [(validate.rules).string = {min_len: 1}];
    string category = 5 [(validate.rules).string = {min_len: 1}];
    string method = 6 [(validate.rules).string = {min_len: 1}];
    double amount = 7 [(validate.rules).double = {}]; // Any amount is valid
}

message CreateTransactionResponse {
    string message = 1;
    int32 code = 2;
}

message CreateBatchTransactionsRequest {
    string request_id = 1 [(validate.rules).string = {uuid: true, min_len: 1}];
    string transaction_date = 2 [(validate.rules).string = {min_len: 1}]; // ISO8601 format
    string posting_date = 3 [(validate.rules).string = {ignore_empty: true, pattern: "^\\d{4}-\\d{2}-\\d{2}$"}]; // YYYY-MM-DD format, optional
    string type = 4 [(validate.rules).string = {min_len: 1}];
    string category = 5 [(validate.rules).string = {min_len: 1}];
    string method = 6 [(validate.rules).string = {min_len: 1}];
    double amount = 7 [(validate.rules).double = {}]; // Any amount is valid
}

message CreateBatchTransactionsResponse {
    string message = 1;
    int32 code = 2;
}

message GetTransactionsCountRequest {
    string request_id = 1 [(validate.rules).string = {uuid: true, min_len: 1}];
}

message GetTransactionsCountResponse {
    int64 count = 1;
    int32 code = 2;
}

message GetTransactionsByTypeAndRequestIDRequest {
    string request_id = 1 [(validate.rules).string = {uuid: true, min_len: 1}];
    string type = 2 [(validate.rules).string = {min_len: 1}];
}

message GetTransactionsByTypeAndRequestIDResponse {
    repeated common.GeneratedTransaction transactions = 1;
    int32 code = 2;
}

message GetTransactionsByMethodAndRequestIDRequest {
    string request_id = 1 [(validate.rules).string = {uuid: true, min_len: 1}];
    string method = 2 [(validate.rules).string = {min_len: 1}];
}

message GetTransactionsByMethodAndRequestIDResponse {
    repeated common.GeneratedTransaction transactions = 1;
    int32 code = 2;
}

message GetTransactionsByRequestIDRequest {
    string request_id = 1 [(validate.rules).string = {uuid: true, min_len: 1}];
}

message GetTransactionsByRequestIDResponse {
    repeated common.GeneratedTransaction transactions = 1;
    int32 code = 2;
}
