syntax = "proto3";

package user;

option go_package = "github.com/IbadT/business_bank_back/pkg/proto";

service UserService {
    rpc Login(LoginRequest) returns (LoginResponse);
    rpc Register(RegisterRequest) returns (RegisterResponse);
    rpc AssociatedCard(AssociatedCardRequest) returns (AssociatedCardResponse);
}

message LoginRequest {
    string email = 1;
    string password = 2;
}

message LoginResponse {
    string access_token = 1;
    string refresh_token = 2;
}

message RegisterRequest {
    string email = 1;
    string password = 2;
}

message RegisterResponse {
    string access_token = 1;
    string refresh_token = 2;
}

message AssociatedCardRequest {
    string associatedCard = 1;
}

message AssociatedCardResponse {
    string message = 1;
    int32 code = 2;
}