// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: balance.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BalanceIssue struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransactionId    string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Date             string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	RequiredBalance  float64                `protobuf:"fixed64,3,opt,name=required_balance,json=requiredBalance,proto3" json:"required_balance,omitempty"`
	AvailableBalance float64                `protobuf:"fixed64,4,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	Shortage         float64                `protobuf:"fixed64,5,opt,name=shortage,proto3" json:"shortage,omitempty"`
	ActionTaken      string                 `protobuf:"bytes,6,opt,name=action_taken,json=actionTaken,proto3" json:"action_taken,omitempty"`
	NewDate          string                 `protobuf:"bytes,7,opt,name=new_date,json=newDate,proto3" json:"new_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BalanceIssue) Reset() {
	*x = BalanceIssue{}
	mi := &file_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceIssue) ProtoMessage() {}

func (x *BalanceIssue) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceIssue.ProtoReflect.Descriptor instead.
func (*BalanceIssue) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceIssue) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *BalanceIssue) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *BalanceIssue) GetRequiredBalance() float64 {
	if x != nil {
		return x.RequiredBalance
	}
	return 0
}

func (x *BalanceIssue) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *BalanceIssue) GetShortage() float64 {
	if x != nil {
		return x.Shortage
	}
	return 0
}

func (x *BalanceIssue) GetActionTaken() string {
	if x != nil {
		return x.ActionTaken
	}
	return ""
}

func (x *BalanceIssue) GetNewDate() string {
	if x != nil {
		return x.NewDate
	}
	return ""
}

type ValidateBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"` // Optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateBalanceRequest) Reset() {
	*x = ValidateBalanceRequest{}
	mi := &file_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateBalanceRequest) ProtoMessage() {}

func (x *ValidateBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateBalanceRequest.ProtoReflect.Descriptor instead.
func (*ValidateBalanceRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateBalanceRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ValidateBalanceRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

type ValidateBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	IsValid       bool                   `protobuf:"varint,2,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Issues        []*BalanceIssue        `protobuf:"bytes,3,rep,name=issues,proto3" json:"issues,omitempty"`
	Code          int32                  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateBalanceResponse) Reset() {
	*x = ValidateBalanceResponse{}
	mi := &file_balance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateBalanceResponse) ProtoMessage() {}

func (x *ValidateBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateBalanceResponse.ProtoReflect.Descriptor instead.
func (*ValidateBalanceResponse) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateBalanceResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ValidateBalanceResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateBalanceResponse) GetIssues() []*BalanceIssue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *ValidateBalanceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type GetBalanceAdjustmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceAdjustmentRequest) Reset() {
	*x = GetBalanceAdjustmentRequest{}
	mi := &file_balance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceAdjustmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceAdjustmentRequest) ProtoMessage() {}

func (x *GetBalanceAdjustmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceAdjustmentRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceAdjustmentRequest) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceAdjustmentRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetBalanceAdjustmentResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	RequestId     string                  `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Transactions  []*GeneratedTransaction `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Code          int32                   `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceAdjustmentResponse) Reset() {
	*x = GetBalanceAdjustmentResponse{}
	mi := &file_balance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceAdjustmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceAdjustmentResponse) ProtoMessage() {}

func (x *GetBalanceAdjustmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_balance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceAdjustmentResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceAdjustmentResponse) Descriptor() ([]byte, []int) {
	return file_balance_proto_rawDescGZIP(), []int{4}
}

func (x *GetBalanceAdjustmentResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetBalanceAdjustmentResponse) GetTransactions() []*GeneratedTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetBalanceAdjustmentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_balance_proto protoreflect.FileDescriptor

const file_balance_proto_rawDesc = "" +
	"\n" +
	"\rbalance.proto\x12\abalance\x1a\fcommon.proto\x1a\x17validate/validate.proto\"\xfb\x01\n" +
	"\fBalanceIssue\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12)\n" +
	"\x10required_balance\x18\x03 \x01(\x01R\x0frequiredBalance\x12+\n" +
	"\x11available_balance\x18\x04 \x01(\x01R\x10availableBalance\x12\x1a\n" +
	"\bshortage\x18\x05 \x01(\x01R\bshortage\x12!\n" +
	"\faction_taken\x18\x06 \x01(\tR\vactionTaken\x12\x19\n" +
	"\bnew_date\x18\a \x01(\tR\anewDate\"\x83\x01\n" +
	"\x16ValidateBalanceRequest\x12)\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\xb0\x01\x01R\trequestId\x12>\n" +
	"\bstrategy\x18\x02 \x01(\tB\"\xfaB\x1fr\x1dR\bpostponeR\x06reduceR\x06hybrid\xd0\x01\x01R\bstrategy\"\x96\x01\n" +
	"\x17ValidateBalanceResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bis_valid\x18\x02 \x01(\bR\aisValid\x12-\n" +
	"\x06issues\x18\x03 \x03(\v2\x15.balance.BalanceIssueR\x06issues\x12\x12\n" +
	"\x04code\x18\x04 \x01(\x05R\x04code\"H\n" +
	"\x1bGetBalanceAdjustmentRequest\x12)\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\xb0\x01\x01R\trequestId\"\x93\x01\n" +
	"\x1cGetBalanceAdjustmentResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12@\n" +
	"\ftransactions\x18\x02 \x03(\v2\x1c.common.GeneratedTransactionR\ftransactions\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code2\xcb\x01\n" +
	"\x0eBalanceService\x12T\n" +
	"\x0fValidateBalance\x12\x1f.balance.ValidateBalanceRequest\x1a .balance.ValidateBalanceResponse\x12c\n" +
	"\x14GetBalanceAdjustment\x12$.balance.GetBalanceAdjustmentRequest\x1a%.balance.GetBalanceAdjustmentResponseB/Z-github.com/IbadT/business_bank_back/pkg/protob\x06proto3"

var (
	file_balance_proto_rawDescOnce sync.Once
	file_balance_proto_rawDescData []byte
)

func file_balance_proto_rawDescGZIP() []byte {
	file_balance_proto_rawDescOnce.Do(func() {
		file_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_balance_proto_rawDesc), len(file_balance_proto_rawDesc)))
	})
	return file_balance_proto_rawDescData
}

var file_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_balance_proto_goTypes = []any{
	(*BalanceIssue)(nil),                 // 0: balance.BalanceIssue
	(*ValidateBalanceRequest)(nil),       // 1: balance.ValidateBalanceRequest
	(*ValidateBalanceResponse)(nil),      // 2: balance.ValidateBalanceResponse
	(*GetBalanceAdjustmentRequest)(nil),  // 3: balance.GetBalanceAdjustmentRequest
	(*GetBalanceAdjustmentResponse)(nil), // 4: balance.GetBalanceAdjustmentResponse
	(*GeneratedTransaction)(nil),         // 5: common.GeneratedTransaction
}
var file_balance_proto_depIdxs = []int32{
	0, // 0: balance.ValidateBalanceResponse.issues:type_name -> balance.BalanceIssue
	5, // 1: balance.GetBalanceAdjustmentResponse.transactions:type_name -> common.GeneratedTransaction
	1, // 2: balance.BalanceService.ValidateBalance:input_type -> balance.ValidateBalanceRequest
	3, // 3: balance.BalanceService.GetBalanceAdjustment:input_type -> balance.GetBalanceAdjustmentRequest
	2, // 4: balance.BalanceService.ValidateBalance:output_type -> balance.ValidateBalanceResponse
	4, // 5: balance.BalanceService.GetBalanceAdjustment:output_type -> balance.GetBalanceAdjustmentResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_balance_proto_init() }
func file_balance_proto_init() {
	if File_balance_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_balance_proto_rawDesc), len(file_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_balance_proto_goTypes,
		DependencyIndexes: file_balance_proto_depIdxs,
		MessageInfos:      file_balance_proto_msgTypes,
	}.Build()
	File_balance_proto = out.File
	file_balance_proto_goTypes = nil
	file_balance_proto_depIdxs = nil
}
