// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: base_amount.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBaseAmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBaseAmountRequest) Reset() {
	*x = GetBaseAmountRequest{}
	mi := &file_base_amount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBaseAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaseAmountRequest) ProtoMessage() {}

func (x *GetBaseAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_amount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaseAmountRequest.ProtoReflect.Descriptor instead.
func (*GetBaseAmountRequest) Descriptor() ([]byte, []int) {
	return file_base_amount_proto_rawDescGZIP(), []int{0}
}

type GetBaseAmountResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MobileBaseAmount    float64                `protobuf:"fixed64,2,opt,name=mobile_base_amount,json=mobileBaseAmount,proto3" json:"mobile_base_amount,omitempty"`
	UtilitiesBaseAmount float64                `protobuf:"fixed64,3,opt,name=utilities_base_amount,json=utilitiesBaseAmount,proto3" json:"utilities_base_amount,omitempty"`
	LeasingBaseAmount   float64                `protobuf:"fixed64,4,opt,name=leasing_base_amount,json=leasingBaseAmount,proto3" json:"leasing_base_amount,omitempty"`
	Code                int32                  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetBaseAmountResponse) Reset() {
	*x = GetBaseAmountResponse{}
	mi := &file_base_amount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBaseAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBaseAmountResponse) ProtoMessage() {}

func (x *GetBaseAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_amount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBaseAmountResponse.ProtoReflect.Descriptor instead.
func (*GetBaseAmountResponse) Descriptor() ([]byte, []int) {
	return file_base_amount_proto_rawDescGZIP(), []int{1}
}

func (x *GetBaseAmountResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBaseAmountResponse) GetMobileBaseAmount() float64 {
	if x != nil {
		return x.MobileBaseAmount
	}
	return 0
}

func (x *GetBaseAmountResponse) GetUtilitiesBaseAmount() float64 {
	if x != nil {
		return x.UtilitiesBaseAmount
	}
	return 0
}

func (x *GetBaseAmountResponse) GetLeasingBaseAmount() float64 {
	if x != nil {
		return x.LeasingBaseAmount
	}
	return 0
}

func (x *GetBaseAmountResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type CalculateMobileAmountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id from cookie
	IsFirstMonth  bool   `protobuf:"varint,1,opt,name=is_first_month,json=isFirstMonth,proto3" json:"is_first_month,omitempty"`
	Month         string `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateMobileAmountRequest) Reset() {
	*x = CalculateMobileAmountRequest{}
	mi := &file_base_amount_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateMobileAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateMobileAmountRequest) ProtoMessage() {}

func (x *CalculateMobileAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_amount_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateMobileAmountRequest.ProtoReflect.Descriptor instead.
func (*CalculateMobileAmountRequest) Descriptor() ([]byte, []int) {
	return file_base_amount_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateMobileAmountRequest) GetIsFirstMonth() bool {
	if x != nil {
		return x.IsFirstMonth
	}
	return false
}

func (x *CalculateMobileAmountRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

type CalculateMobileAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	IsFirstMonth  bool                   `protobuf:"varint,3,opt,name=is_first_month,json=isFirstMonth,proto3" json:"is_first_month,omitempty"`
	Code          int32                  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateMobileAmountResponse) Reset() {
	*x = CalculateMobileAmountResponse{}
	mi := &file_base_amount_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateMobileAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateMobileAmountResponse) ProtoMessage() {}

func (x *CalculateMobileAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_amount_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateMobileAmountResponse.ProtoReflect.Descriptor instead.
func (*CalculateMobileAmountResponse) Descriptor() ([]byte, []int) {
	return file_base_amount_proto_rawDescGZIP(), []int{3}
}

func (x *CalculateMobileAmountResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CalculateMobileAmountResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CalculateMobileAmountResponse) GetIsFirstMonth() bool {
	if x != nil {
		return x.IsFirstMonth
	}
	return false
}

func (x *CalculateMobileAmountResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type CalculateUtilitiesAmountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id from cookie
	IsFirstMonth  bool   `protobuf:"varint,1,opt,name=is_first_month,json=isFirstMonth,proto3" json:"is_first_month,omitempty"`
	Month         string `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateUtilitiesAmountRequest) Reset() {
	*x = CalculateUtilitiesAmountRequest{}
	mi := &file_base_amount_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateUtilitiesAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateUtilitiesAmountRequest) ProtoMessage() {}

func (x *CalculateUtilitiesAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_amount_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateUtilitiesAmountRequest.ProtoReflect.Descriptor instead.
func (*CalculateUtilitiesAmountRequest) Descriptor() ([]byte, []int) {
	return file_base_amount_proto_rawDescGZIP(), []int{4}
}

func (x *CalculateUtilitiesAmountRequest) GetIsFirstMonth() bool {
	if x != nil {
		return x.IsFirstMonth
	}
	return false
}

func (x *CalculateUtilitiesAmountRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

type CalculateUtilitiesAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	IsFirstMonth  bool                   `protobuf:"varint,3,opt,name=is_first_month,json=isFirstMonth,proto3" json:"is_first_month,omitempty"`
	Code          int32                  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateUtilitiesAmountResponse) Reset() {
	*x = CalculateUtilitiesAmountResponse{}
	mi := &file_base_amount_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateUtilitiesAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateUtilitiesAmountResponse) ProtoMessage() {}

func (x *CalculateUtilitiesAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_amount_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateUtilitiesAmountResponse.ProtoReflect.Descriptor instead.
func (*CalculateUtilitiesAmountResponse) Descriptor() ([]byte, []int) {
	return file_base_amount_proto_rawDescGZIP(), []int{5}
}

func (x *CalculateUtilitiesAmountResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CalculateUtilitiesAmountResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CalculateUtilitiesAmountResponse) GetIsFirstMonth() bool {
	if x != nil {
		return x.IsFirstMonth
	}
	return false
}

func (x *CalculateUtilitiesAmountResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type CalculateLeasingAmountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id from cookie
	IsFirstMonth  bool    `protobuf:"varint,1,opt,name=is_first_month,json=isFirstMonth,proto3" json:"is_first_month,omitempty"`
	Month         string  `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	Turnover      float64 `protobuf:"fixed64,3,opt,name=turnover,proto3" json:"turnover,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateLeasingAmountRequest) Reset() {
	*x = CalculateLeasingAmountRequest{}
	mi := &file_base_amount_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateLeasingAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateLeasingAmountRequest) ProtoMessage() {}

func (x *CalculateLeasingAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_amount_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateLeasingAmountRequest.ProtoReflect.Descriptor instead.
func (*CalculateLeasingAmountRequest) Descriptor() ([]byte, []int) {
	return file_base_amount_proto_rawDescGZIP(), []int{6}
}

func (x *CalculateLeasingAmountRequest) GetIsFirstMonth() bool {
	if x != nil {
		return x.IsFirstMonth
	}
	return false
}

func (x *CalculateLeasingAmountRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *CalculateLeasingAmountRequest) GetTurnover() float64 {
	if x != nil {
		return x.Turnover
	}
	return 0
}

type CalculateLeasingAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	IsFirstMonth  bool                   `protobuf:"varint,3,opt,name=is_first_month,json=isFirstMonth,proto3" json:"is_first_month,omitempty"`
	Turnover      float64                `protobuf:"fixed64,4,opt,name=turnover,proto3" json:"turnover,omitempty"`
	Code          int32                  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateLeasingAmountResponse) Reset() {
	*x = CalculateLeasingAmountResponse{}
	mi := &file_base_amount_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateLeasingAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateLeasingAmountResponse) ProtoMessage() {}

func (x *CalculateLeasingAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_amount_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateLeasingAmountResponse.ProtoReflect.Descriptor instead.
func (*CalculateLeasingAmountResponse) Descriptor() ([]byte, []int) {
	return file_base_amount_proto_rawDescGZIP(), []int{7}
}

func (x *CalculateLeasingAmountResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CalculateLeasingAmountResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CalculateLeasingAmountResponse) GetIsFirstMonth() bool {
	if x != nil {
		return x.IsFirstMonth
	}
	return false
}

func (x *CalculateLeasingAmountResponse) GetTurnover() float64 {
	if x != nil {
		return x.Turnover
	}
	return 0
}

func (x *CalculateLeasingAmountResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ResetMobileBaseAmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetMobileBaseAmountRequest) Reset() {
	*x = ResetMobileBaseAmountRequest{}
	mi := &file_base_amount_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetMobileBaseAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetMobileBaseAmountRequest) ProtoMessage() {}

func (x *ResetMobileBaseAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_amount_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetMobileBaseAmountRequest.ProtoReflect.Descriptor instead.
func (*ResetMobileBaseAmountRequest) Descriptor() ([]byte, []int) {
	return file_base_amount_proto_rawDescGZIP(), []int{8}
}

type ResetMobileBaseAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetMobileBaseAmountResponse) Reset() {
	*x = ResetMobileBaseAmountResponse{}
	mi := &file_base_amount_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetMobileBaseAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetMobileBaseAmountResponse) ProtoMessage() {}

func (x *ResetMobileBaseAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_amount_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetMobileBaseAmountResponse.ProtoReflect.Descriptor instead.
func (*ResetMobileBaseAmountResponse) Descriptor() ([]byte, []int) {
	return file_base_amount_proto_rawDescGZIP(), []int{9}
}

func (x *ResetMobileBaseAmountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResetMobileBaseAmountResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ResetUtilitiesBaseAmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetUtilitiesBaseAmountRequest) Reset() {
	*x = ResetUtilitiesBaseAmountRequest{}
	mi := &file_base_amount_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetUtilitiesBaseAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUtilitiesBaseAmountRequest) ProtoMessage() {}

func (x *ResetUtilitiesBaseAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_amount_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUtilitiesBaseAmountRequest.ProtoReflect.Descriptor instead.
func (*ResetUtilitiesBaseAmountRequest) Descriptor() ([]byte, []int) {
	return file_base_amount_proto_rawDescGZIP(), []int{10}
}

type ResetUtilitiesBaseAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetUtilitiesBaseAmountResponse) Reset() {
	*x = ResetUtilitiesBaseAmountResponse{}
	mi := &file_base_amount_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetUtilitiesBaseAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUtilitiesBaseAmountResponse) ProtoMessage() {}

func (x *ResetUtilitiesBaseAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_amount_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUtilitiesBaseAmountResponse.ProtoReflect.Descriptor instead.
func (*ResetUtilitiesBaseAmountResponse) Descriptor() ([]byte, []int) {
	return file_base_amount_proto_rawDescGZIP(), []int{11}
}

func (x *ResetUtilitiesBaseAmountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResetUtilitiesBaseAmountResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ResetLeasingBaseAmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetLeasingBaseAmountRequest) Reset() {
	*x = ResetLeasingBaseAmountRequest{}
	mi := &file_base_amount_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetLeasingBaseAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetLeasingBaseAmountRequest) ProtoMessage() {}

func (x *ResetLeasingBaseAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_amount_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetLeasingBaseAmountRequest.ProtoReflect.Descriptor instead.
func (*ResetLeasingBaseAmountRequest) Descriptor() ([]byte, []int) {
	return file_base_amount_proto_rawDescGZIP(), []int{12}
}

type ResetLeasingBaseAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetLeasingBaseAmountResponse) Reset() {
	*x = ResetLeasingBaseAmountResponse{}
	mi := &file_base_amount_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetLeasingBaseAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetLeasingBaseAmountResponse) ProtoMessage() {}

func (x *ResetLeasingBaseAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_amount_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetLeasingBaseAmountResponse.ProtoReflect.Descriptor instead.
func (*ResetLeasingBaseAmountResponse) Descriptor() ([]byte, []int) {
	return file_base_amount_proto_rawDescGZIP(), []int{13}
}

func (x *ResetLeasingBaseAmountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResetLeasingBaseAmountResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_base_amount_proto protoreflect.FileDescriptor

const file_base_amount_proto_rawDesc = "" +
	"\n" +
	"\x11base_amount.proto\x12\vbase_amount\"\x16\n" +
	"\x14GetBaseAmountRequest\"\xd6\x01\n" +
	"\x15GetBaseAmountResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12,\n" +
	"\x12mobile_base_amount\x18\x02 \x01(\x01R\x10mobileBaseAmount\x122\n" +
	"\x15utilities_base_amount\x18\x03 \x01(\x01R\x13utilitiesBaseAmount\x12.\n" +
	"\x13leasing_base_amount\x18\x04 \x01(\x01R\x11leasingBaseAmount\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x05R\x04code\"Z\n" +
	"\x1cCalculateMobileAmountRequest\x12$\n" +
	"\x0eis_first_month\x18\x01 \x01(\bR\fisFirstMonth\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\"\x8a\x01\n" +
	"\x1dCalculateMobileAmountResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12$\n" +
	"\x0eis_first_month\x18\x03 \x01(\bR\fisFirstMonth\x12\x12\n" +
	"\x04code\x18\x04 \x01(\x05R\x04code\"]\n" +
	"\x1fCalculateUtilitiesAmountRequest\x12$\n" +
	"\x0eis_first_month\x18\x01 \x01(\bR\fisFirstMonth\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\"\x8d\x01\n" +
	" CalculateUtilitiesAmountResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12$\n" +
	"\x0eis_first_month\x18\x03 \x01(\bR\fisFirstMonth\x12\x12\n" +
	"\x04code\x18\x04 \x01(\x05R\x04code\"w\n" +
	"\x1dCalculateLeasingAmountRequest\x12$\n" +
	"\x0eis_first_month\x18\x01 \x01(\bR\fisFirstMonth\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\x12\x1a\n" +
	"\bturnover\x18\x03 \x01(\x01R\bturnover\"\xa7\x01\n" +
	"\x1eCalculateLeasingAmountResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12$\n" +
	"\x0eis_first_month\x18\x03 \x01(\bR\fisFirstMonth\x12\x1a\n" +
	"\bturnover\x18\x04 \x01(\x01R\bturnover\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x05R\x04code\"\x1e\n" +
	"\x1cResetMobileBaseAmountRequest\"M\n" +
	"\x1dResetMobileBaseAmountResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"!\n" +
	"\x1fResetUtilitiesBaseAmountRequest\"P\n" +
	" ResetUtilitiesBaseAmountResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"\x1f\n" +
	"\x1dResetLeasingBaseAmountRequest\"N\n" +
	"\x1eResetLeasingBaseAmountResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code2\xa3\x06\n" +
	"\x11BaseAmountService\x12V\n" +
	"\rGetBaseAmount\x12!.base_amount.GetBaseAmountRequest\x1a\".base_amount.GetBaseAmountResponse\x12n\n" +
	"\x15CalculateMobileAmount\x12).base_amount.CalculateMobileAmountRequest\x1a*.base_amount.CalculateMobileAmountResponse\x12w\n" +
	"\x18CalculateUtilitiesAmount\x12,.base_amount.CalculateUtilitiesAmountRequest\x1a-.base_amount.CalculateUtilitiesAmountResponse\x12q\n" +
	"\x16CalculateLeasingAmount\x12*.base_amount.CalculateLeasingAmountRequest\x1a+.base_amount.CalculateLeasingAmountResponse\x12n\n" +
	"\x15ResetMobileBaseAmount\x12).base_amount.ResetMobileBaseAmountRequest\x1a*.base_amount.ResetMobileBaseAmountResponse\x12w\n" +
	"\x18ResetUtilitiesBaseAmount\x12,.base_amount.ResetUtilitiesBaseAmountRequest\x1a-.base_amount.ResetUtilitiesBaseAmountResponse\x12q\n" +
	"\x16ResetLeasingBaseAmount\x12*.base_amount.ResetLeasingBaseAmountRequest\x1a+.base_amount.ResetLeasingBaseAmountResponseB/Z-github.com/IbadT/business_bank_back/pkg/protob\x06proto3"

var (
	file_base_amount_proto_rawDescOnce sync.Once
	file_base_amount_proto_rawDescData []byte
)

func file_base_amount_proto_rawDescGZIP() []byte {
	file_base_amount_proto_rawDescOnce.Do(func() {
		file_base_amount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_amount_proto_rawDesc), len(file_base_amount_proto_rawDesc)))
	})
	return file_base_amount_proto_rawDescData
}

var file_base_amount_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_base_amount_proto_goTypes = []any{
	(*GetBaseAmountRequest)(nil),             // 0: base_amount.GetBaseAmountRequest
	(*GetBaseAmountResponse)(nil),            // 1: base_amount.GetBaseAmountResponse
	(*CalculateMobileAmountRequest)(nil),     // 2: base_amount.CalculateMobileAmountRequest
	(*CalculateMobileAmountResponse)(nil),    // 3: base_amount.CalculateMobileAmountResponse
	(*CalculateUtilitiesAmountRequest)(nil),  // 4: base_amount.CalculateUtilitiesAmountRequest
	(*CalculateUtilitiesAmountResponse)(nil), // 5: base_amount.CalculateUtilitiesAmountResponse
	(*CalculateLeasingAmountRequest)(nil),    // 6: base_amount.CalculateLeasingAmountRequest
	(*CalculateLeasingAmountResponse)(nil),   // 7: base_amount.CalculateLeasingAmountResponse
	(*ResetMobileBaseAmountRequest)(nil),     // 8: base_amount.ResetMobileBaseAmountRequest
	(*ResetMobileBaseAmountResponse)(nil),    // 9: base_amount.ResetMobileBaseAmountResponse
	(*ResetUtilitiesBaseAmountRequest)(nil),  // 10: base_amount.ResetUtilitiesBaseAmountRequest
	(*ResetUtilitiesBaseAmountResponse)(nil), // 11: base_amount.ResetUtilitiesBaseAmountResponse
	(*ResetLeasingBaseAmountRequest)(nil),    // 12: base_amount.ResetLeasingBaseAmountRequest
	(*ResetLeasingBaseAmountResponse)(nil),   // 13: base_amount.ResetLeasingBaseAmountResponse
}
var file_base_amount_proto_depIdxs = []int32{
	0,  // 0: base_amount.BaseAmountService.GetBaseAmount:input_type -> base_amount.GetBaseAmountRequest
	2,  // 1: base_amount.BaseAmountService.CalculateMobileAmount:input_type -> base_amount.CalculateMobileAmountRequest
	4,  // 2: base_amount.BaseAmountService.CalculateUtilitiesAmount:input_type -> base_amount.CalculateUtilitiesAmountRequest
	6,  // 3: base_amount.BaseAmountService.CalculateLeasingAmount:input_type -> base_amount.CalculateLeasingAmountRequest
	8,  // 4: base_amount.BaseAmountService.ResetMobileBaseAmount:input_type -> base_amount.ResetMobileBaseAmountRequest
	10, // 5: base_amount.BaseAmountService.ResetUtilitiesBaseAmount:input_type -> base_amount.ResetUtilitiesBaseAmountRequest
	12, // 6: base_amount.BaseAmountService.ResetLeasingBaseAmount:input_type -> base_amount.ResetLeasingBaseAmountRequest
	1,  // 7: base_amount.BaseAmountService.GetBaseAmount:output_type -> base_amount.GetBaseAmountResponse
	3,  // 8: base_amount.BaseAmountService.CalculateMobileAmount:output_type -> base_amount.CalculateMobileAmountResponse
	5,  // 9: base_amount.BaseAmountService.CalculateUtilitiesAmount:output_type -> base_amount.CalculateUtilitiesAmountResponse
	7,  // 10: base_amount.BaseAmountService.CalculateLeasingAmount:output_type -> base_amount.CalculateLeasingAmountResponse
	9,  // 11: base_amount.BaseAmountService.ResetMobileBaseAmount:output_type -> base_amount.ResetMobileBaseAmountResponse
	11, // 12: base_amount.BaseAmountService.ResetUtilitiesBaseAmount:output_type -> base_amount.ResetUtilitiesBaseAmountResponse
	13, // 13: base_amount.BaseAmountService.ResetLeasingBaseAmount:output_type -> base_amount.ResetLeasingBaseAmountResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_base_amount_proto_init() }
func file_base_amount_proto_init() {
	if File_base_amount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_amount_proto_rawDesc), len(file_base_amount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_amount_proto_goTypes,
		DependencyIndexes: file_base_amount_proto_depIdxs,
		MessageInfos:      file_base_amount_proto_msgTypes,
	}.Build()
	File_base_amount_proto = out.File
	file_base_amount_proto_goTypes = nil
	file_base_amount_proto_depIdxs = nil
}
