// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: base_amount.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetBaseAmountRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetBaseAmountRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBaseAmountRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBaseAmountRequestMultiError, or nil if none found.
func (m *GetBaseAmountRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBaseAmountRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetBaseAmountRequestMultiError(errors)
	}

	return nil
}

// GetBaseAmountRequestMultiError is an error wrapping multiple validation
// errors returned by GetBaseAmountRequest.ValidateAll() if the designated
// constraints aren't met.
type GetBaseAmountRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBaseAmountRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBaseAmountRequestMultiError) AllErrors() []error { return m }

// GetBaseAmountRequestValidationError is the validation error returned by
// GetBaseAmountRequest.Validate if the designated constraints aren't met.
type GetBaseAmountRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBaseAmountRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBaseAmountRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBaseAmountRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBaseAmountRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBaseAmountRequestValidationError) ErrorName() string {
	return "GetBaseAmountRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetBaseAmountRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBaseAmountRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBaseAmountRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBaseAmountRequestValidationError{}

// Validate checks the field values on GetBaseAmountResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetBaseAmountResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBaseAmountResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBaseAmountResponseMultiError, or nil if none found.
func (m *GetBaseAmountResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBaseAmountResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for MobileBaseAmount

	// no validation rules for UtilitiesBaseAmount

	// no validation rules for LeasingBaseAmount

	// no validation rules for Code

	if len(errors) > 0 {
		return GetBaseAmountResponseMultiError(errors)
	}

	return nil
}

// GetBaseAmountResponseMultiError is an error wrapping multiple validation
// errors returned by GetBaseAmountResponse.ValidateAll() if the designated
// constraints aren't met.
type GetBaseAmountResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBaseAmountResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBaseAmountResponseMultiError) AllErrors() []error { return m }

// GetBaseAmountResponseValidationError is the validation error returned by
// GetBaseAmountResponse.Validate if the designated constraints aren't met.
type GetBaseAmountResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBaseAmountResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBaseAmountResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBaseAmountResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBaseAmountResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBaseAmountResponseValidationError) ErrorName() string {
	return "GetBaseAmountResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetBaseAmountResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBaseAmountResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBaseAmountResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBaseAmountResponseValidationError{}

// Validate checks the field values on CalculateMobileAmountRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CalculateMobileAmountRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CalculateMobileAmountRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CalculateMobileAmountRequestMultiError, or nil if none found.
func (m *CalculateMobileAmountRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CalculateMobileAmountRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsFirstMonth

	if m.GetMonth() != "" {

		if !_CalculateMobileAmountRequest_Month_Pattern.MatchString(m.GetMonth()) {
			err := CalculateMobileAmountRequestValidationError{
				field:  "Month",
				reason: "value does not match regex pattern \"^\\\\d{4}-\\\\d{2}$\"",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return CalculateMobileAmountRequestMultiError(errors)
	}

	return nil
}

// CalculateMobileAmountRequestMultiError is an error wrapping multiple
// validation errors returned by CalculateMobileAmountRequest.ValidateAll() if
// the designated constraints aren't met.
type CalculateMobileAmountRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CalculateMobileAmountRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CalculateMobileAmountRequestMultiError) AllErrors() []error { return m }

// CalculateMobileAmountRequestValidationError is the validation error returned
// by CalculateMobileAmountRequest.Validate if the designated constraints
// aren't met.
type CalculateMobileAmountRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CalculateMobileAmountRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CalculateMobileAmountRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CalculateMobileAmountRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CalculateMobileAmountRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CalculateMobileAmountRequestValidationError) ErrorName() string {
	return "CalculateMobileAmountRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CalculateMobileAmountRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCalculateMobileAmountRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CalculateMobileAmountRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CalculateMobileAmountRequestValidationError{}

var _CalculateMobileAmountRequest_Month_Pattern = regexp.MustCompile("^\\d{4}-\\d{2}$")

// Validate checks the field values on CalculateMobileAmountResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CalculateMobileAmountResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CalculateMobileAmountResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CalculateMobileAmountResponseMultiError, or nil if none found.
func (m *CalculateMobileAmountResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CalculateMobileAmountResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Amount

	// no validation rules for IsFirstMonth

	// no validation rules for Code

	if len(errors) > 0 {
		return CalculateMobileAmountResponseMultiError(errors)
	}

	return nil
}

// CalculateMobileAmountResponseMultiError is an error wrapping multiple
// validation errors returned by CalculateMobileAmountResponse.ValidateAll()
// if the designated constraints aren't met.
type CalculateMobileAmountResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CalculateMobileAmountResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CalculateMobileAmountResponseMultiError) AllErrors() []error { return m }

// CalculateMobileAmountResponseValidationError is the validation error
// returned by CalculateMobileAmountResponse.Validate if the designated
// constraints aren't met.
type CalculateMobileAmountResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CalculateMobileAmountResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CalculateMobileAmountResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CalculateMobileAmountResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CalculateMobileAmountResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CalculateMobileAmountResponseValidationError) ErrorName() string {
	return "CalculateMobileAmountResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CalculateMobileAmountResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCalculateMobileAmountResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CalculateMobileAmountResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CalculateMobileAmountResponseValidationError{}

// Validate checks the field values on CalculateUtilitiesAmountRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CalculateUtilitiesAmountRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CalculateUtilitiesAmountRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CalculateUtilitiesAmountRequestMultiError, or nil if none found.
func (m *CalculateUtilitiesAmountRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CalculateUtilitiesAmountRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsFirstMonth

	if m.GetMonth() != "" {

		if !_CalculateUtilitiesAmountRequest_Month_Pattern.MatchString(m.GetMonth()) {
			err := CalculateUtilitiesAmountRequestValidationError{
				field:  "Month",
				reason: "value does not match regex pattern \"^\\\\d{4}-\\\\d{2}$\"",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return CalculateUtilitiesAmountRequestMultiError(errors)
	}

	return nil
}

// CalculateUtilitiesAmountRequestMultiError is an error wrapping multiple
// validation errors returned by CalculateUtilitiesAmountRequest.ValidateAll()
// if the designated constraints aren't met.
type CalculateUtilitiesAmountRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CalculateUtilitiesAmountRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CalculateUtilitiesAmountRequestMultiError) AllErrors() []error { return m }

// CalculateUtilitiesAmountRequestValidationError is the validation error
// returned by CalculateUtilitiesAmountRequest.Validate if the designated
// constraints aren't met.
type CalculateUtilitiesAmountRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CalculateUtilitiesAmountRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CalculateUtilitiesAmountRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CalculateUtilitiesAmountRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CalculateUtilitiesAmountRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CalculateUtilitiesAmountRequestValidationError) ErrorName() string {
	return "CalculateUtilitiesAmountRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CalculateUtilitiesAmountRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCalculateUtilitiesAmountRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CalculateUtilitiesAmountRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CalculateUtilitiesAmountRequestValidationError{}

var _CalculateUtilitiesAmountRequest_Month_Pattern = regexp.MustCompile("^\\d{4}-\\d{2}$")

// Validate checks the field values on CalculateUtilitiesAmountResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *CalculateUtilitiesAmountResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CalculateUtilitiesAmountResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CalculateUtilitiesAmountResponseMultiError, or nil if none found.
func (m *CalculateUtilitiesAmountResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CalculateUtilitiesAmountResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Amount

	// no validation rules for IsFirstMonth

	// no validation rules for Code

	if len(errors) > 0 {
		return CalculateUtilitiesAmountResponseMultiError(errors)
	}

	return nil
}

// CalculateUtilitiesAmountResponseMultiError is an error wrapping multiple
// validation errors returned by
// CalculateUtilitiesAmountResponse.ValidateAll() if the designated
// constraints aren't met.
type CalculateUtilitiesAmountResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CalculateUtilitiesAmountResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CalculateUtilitiesAmountResponseMultiError) AllErrors() []error { return m }

// CalculateUtilitiesAmountResponseValidationError is the validation error
// returned by CalculateUtilitiesAmountResponse.Validate if the designated
// constraints aren't met.
type CalculateUtilitiesAmountResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CalculateUtilitiesAmountResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CalculateUtilitiesAmountResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CalculateUtilitiesAmountResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CalculateUtilitiesAmountResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CalculateUtilitiesAmountResponseValidationError) ErrorName() string {
	return "CalculateUtilitiesAmountResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CalculateUtilitiesAmountResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCalculateUtilitiesAmountResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CalculateUtilitiesAmountResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CalculateUtilitiesAmountResponseValidationError{}

// Validate checks the field values on CalculateLeasingAmountRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CalculateLeasingAmountRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CalculateLeasingAmountRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CalculateLeasingAmountRequestMultiError, or nil if none found.
func (m *CalculateLeasingAmountRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CalculateLeasingAmountRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsFirstMonth

	if m.GetMonth() != "" {

		if !_CalculateLeasingAmountRequest_Month_Pattern.MatchString(m.GetMonth()) {
			err := CalculateLeasingAmountRequestValidationError{
				field:  "Month",
				reason: "value does not match regex pattern \"^\\\\d{4}-\\\\d{2}$\"",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.GetTurnover() != 0 {

		if m.GetTurnover() <= 0 {
			err := CalculateLeasingAmountRequestValidationError{
				field:  "Turnover",
				reason: "value must be greater than 0",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return CalculateLeasingAmountRequestMultiError(errors)
	}

	return nil
}

// CalculateLeasingAmountRequestMultiError is an error wrapping multiple
// validation errors returned by CalculateLeasingAmountRequest.ValidateAll()
// if the designated constraints aren't met.
type CalculateLeasingAmountRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CalculateLeasingAmountRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CalculateLeasingAmountRequestMultiError) AllErrors() []error { return m }

// CalculateLeasingAmountRequestValidationError is the validation error
// returned by CalculateLeasingAmountRequest.Validate if the designated
// constraints aren't met.
type CalculateLeasingAmountRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CalculateLeasingAmountRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CalculateLeasingAmountRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CalculateLeasingAmountRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CalculateLeasingAmountRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CalculateLeasingAmountRequestValidationError) ErrorName() string {
	return "CalculateLeasingAmountRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CalculateLeasingAmountRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCalculateLeasingAmountRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CalculateLeasingAmountRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CalculateLeasingAmountRequestValidationError{}

var _CalculateLeasingAmountRequest_Month_Pattern = regexp.MustCompile("^\\d{4}-\\d{2}$")

// Validate checks the field values on CalculateLeasingAmountResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CalculateLeasingAmountResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CalculateLeasingAmountResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CalculateLeasingAmountResponseMultiError, or nil if none found.
func (m *CalculateLeasingAmountResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CalculateLeasingAmountResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Amount

	// no validation rules for IsFirstMonth

	// no validation rules for Turnover

	// no validation rules for Code

	if len(errors) > 0 {
		return CalculateLeasingAmountResponseMultiError(errors)
	}

	return nil
}

// CalculateLeasingAmountResponseMultiError is an error wrapping multiple
// validation errors returned by CalculateLeasingAmountResponse.ValidateAll()
// if the designated constraints aren't met.
type CalculateLeasingAmountResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CalculateLeasingAmountResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CalculateLeasingAmountResponseMultiError) AllErrors() []error { return m }

// CalculateLeasingAmountResponseValidationError is the validation error
// returned by CalculateLeasingAmountResponse.Validate if the designated
// constraints aren't met.
type CalculateLeasingAmountResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CalculateLeasingAmountResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CalculateLeasingAmountResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CalculateLeasingAmountResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CalculateLeasingAmountResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CalculateLeasingAmountResponseValidationError) ErrorName() string {
	return "CalculateLeasingAmountResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CalculateLeasingAmountResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCalculateLeasingAmountResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CalculateLeasingAmountResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CalculateLeasingAmountResponseValidationError{}

// Validate checks the field values on ResetMobileBaseAmountRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResetMobileBaseAmountRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResetMobileBaseAmountRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResetMobileBaseAmountRequestMultiError, or nil if none found.
func (m *ResetMobileBaseAmountRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ResetMobileBaseAmountRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ResetMobileBaseAmountRequestMultiError(errors)
	}

	return nil
}

// ResetMobileBaseAmountRequestMultiError is an error wrapping multiple
// validation errors returned by ResetMobileBaseAmountRequest.ValidateAll() if
// the designated constraints aren't met.
type ResetMobileBaseAmountRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResetMobileBaseAmountRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResetMobileBaseAmountRequestMultiError) AllErrors() []error { return m }

// ResetMobileBaseAmountRequestValidationError is the validation error returned
// by ResetMobileBaseAmountRequest.Validate if the designated constraints
// aren't met.
type ResetMobileBaseAmountRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResetMobileBaseAmountRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResetMobileBaseAmountRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResetMobileBaseAmountRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResetMobileBaseAmountRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResetMobileBaseAmountRequestValidationError) ErrorName() string {
	return "ResetMobileBaseAmountRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ResetMobileBaseAmountRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResetMobileBaseAmountRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResetMobileBaseAmountRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResetMobileBaseAmountRequestValidationError{}

// Validate checks the field values on ResetMobileBaseAmountResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResetMobileBaseAmountResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResetMobileBaseAmountResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ResetMobileBaseAmountResponseMultiError, or nil if none found.
func (m *ResetMobileBaseAmountResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ResetMobileBaseAmountResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	// no validation rules for Code

	if len(errors) > 0 {
		return ResetMobileBaseAmountResponseMultiError(errors)
	}

	return nil
}

// ResetMobileBaseAmountResponseMultiError is an error wrapping multiple
// validation errors returned by ResetMobileBaseAmountResponse.ValidateAll()
// if the designated constraints aren't met.
type ResetMobileBaseAmountResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResetMobileBaseAmountResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResetMobileBaseAmountResponseMultiError) AllErrors() []error { return m }

// ResetMobileBaseAmountResponseValidationError is the validation error
// returned by ResetMobileBaseAmountResponse.Validate if the designated
// constraints aren't met.
type ResetMobileBaseAmountResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResetMobileBaseAmountResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResetMobileBaseAmountResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResetMobileBaseAmountResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResetMobileBaseAmountResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResetMobileBaseAmountResponseValidationError) ErrorName() string {
	return "ResetMobileBaseAmountResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ResetMobileBaseAmountResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResetMobileBaseAmountResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResetMobileBaseAmountResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResetMobileBaseAmountResponseValidationError{}

// Validate checks the field values on ResetUtilitiesBaseAmountRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResetUtilitiesBaseAmountRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResetUtilitiesBaseAmountRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ResetUtilitiesBaseAmountRequestMultiError, or nil if none found.
func (m *ResetUtilitiesBaseAmountRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ResetUtilitiesBaseAmountRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ResetUtilitiesBaseAmountRequestMultiError(errors)
	}

	return nil
}

// ResetUtilitiesBaseAmountRequestMultiError is an error wrapping multiple
// validation errors returned by ResetUtilitiesBaseAmountRequest.ValidateAll()
// if the designated constraints aren't met.
type ResetUtilitiesBaseAmountRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResetUtilitiesBaseAmountRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResetUtilitiesBaseAmountRequestMultiError) AllErrors() []error { return m }

// ResetUtilitiesBaseAmountRequestValidationError is the validation error
// returned by ResetUtilitiesBaseAmountRequest.Validate if the designated
// constraints aren't met.
type ResetUtilitiesBaseAmountRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResetUtilitiesBaseAmountRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResetUtilitiesBaseAmountRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResetUtilitiesBaseAmountRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResetUtilitiesBaseAmountRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResetUtilitiesBaseAmountRequestValidationError) ErrorName() string {
	return "ResetUtilitiesBaseAmountRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ResetUtilitiesBaseAmountRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResetUtilitiesBaseAmountRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResetUtilitiesBaseAmountRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResetUtilitiesBaseAmountRequestValidationError{}

// Validate checks the field values on ResetUtilitiesBaseAmountResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ResetUtilitiesBaseAmountResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResetUtilitiesBaseAmountResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ResetUtilitiesBaseAmountResponseMultiError, or nil if none found.
func (m *ResetUtilitiesBaseAmountResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ResetUtilitiesBaseAmountResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	// no validation rules for Code

	if len(errors) > 0 {
		return ResetUtilitiesBaseAmountResponseMultiError(errors)
	}

	return nil
}

// ResetUtilitiesBaseAmountResponseMultiError is an error wrapping multiple
// validation errors returned by
// ResetUtilitiesBaseAmountResponse.ValidateAll() if the designated
// constraints aren't met.
type ResetUtilitiesBaseAmountResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResetUtilitiesBaseAmountResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResetUtilitiesBaseAmountResponseMultiError) AllErrors() []error { return m }

// ResetUtilitiesBaseAmountResponseValidationError is the validation error
// returned by ResetUtilitiesBaseAmountResponse.Validate if the designated
// constraints aren't met.
type ResetUtilitiesBaseAmountResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResetUtilitiesBaseAmountResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResetUtilitiesBaseAmountResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResetUtilitiesBaseAmountResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResetUtilitiesBaseAmountResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResetUtilitiesBaseAmountResponseValidationError) ErrorName() string {
	return "ResetUtilitiesBaseAmountResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ResetUtilitiesBaseAmountResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResetUtilitiesBaseAmountResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResetUtilitiesBaseAmountResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResetUtilitiesBaseAmountResponseValidationError{}

// Validate checks the field values on ResetLeasingBaseAmountRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResetLeasingBaseAmountRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResetLeasingBaseAmountRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ResetLeasingBaseAmountRequestMultiError, or nil if none found.
func (m *ResetLeasingBaseAmountRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ResetLeasingBaseAmountRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ResetLeasingBaseAmountRequestMultiError(errors)
	}

	return nil
}

// ResetLeasingBaseAmountRequestMultiError is an error wrapping multiple
// validation errors returned by ResetLeasingBaseAmountRequest.ValidateAll()
// if the designated constraints aren't met.
type ResetLeasingBaseAmountRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResetLeasingBaseAmountRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResetLeasingBaseAmountRequestMultiError) AllErrors() []error { return m }

// ResetLeasingBaseAmountRequestValidationError is the validation error
// returned by ResetLeasingBaseAmountRequest.Validate if the designated
// constraints aren't met.
type ResetLeasingBaseAmountRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResetLeasingBaseAmountRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResetLeasingBaseAmountRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResetLeasingBaseAmountRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResetLeasingBaseAmountRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResetLeasingBaseAmountRequestValidationError) ErrorName() string {
	return "ResetLeasingBaseAmountRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ResetLeasingBaseAmountRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResetLeasingBaseAmountRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResetLeasingBaseAmountRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResetLeasingBaseAmountRequestValidationError{}

// Validate checks the field values on ResetLeasingBaseAmountResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResetLeasingBaseAmountResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResetLeasingBaseAmountResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ResetLeasingBaseAmountResponseMultiError, or nil if none found.
func (m *ResetLeasingBaseAmountResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ResetLeasingBaseAmountResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	// no validation rules for Code

	if len(errors) > 0 {
		return ResetLeasingBaseAmountResponseMultiError(errors)
	}

	return nil
}

// ResetLeasingBaseAmountResponseMultiError is an error wrapping multiple
// validation errors returned by ResetLeasingBaseAmountResponse.ValidateAll()
// if the designated constraints aren't met.
type ResetLeasingBaseAmountResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResetLeasingBaseAmountResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResetLeasingBaseAmountResponseMultiError) AllErrors() []error { return m }

// ResetLeasingBaseAmountResponseValidationError is the validation error
// returned by ResetLeasingBaseAmountResponse.Validate if the designated
// constraints aren't met.
type ResetLeasingBaseAmountResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResetLeasingBaseAmountResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResetLeasingBaseAmountResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResetLeasingBaseAmountResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResetLeasingBaseAmountResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResetLeasingBaseAmountResponseValidationError) ErrorName() string {
	return "ResetLeasingBaseAmountResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ResetLeasingBaseAmountResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResetLeasingBaseAmountResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResetLeasingBaseAmountResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResetLeasingBaseAmountResponseValidationError{}
