// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: base_amount.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BaseAmountService_GetBaseAmount_FullMethodName            = "/base_amount.BaseAmountService/GetBaseAmount"
	BaseAmountService_CalculateMobileAmount_FullMethodName    = "/base_amount.BaseAmountService/CalculateMobileAmount"
	BaseAmountService_CalculateUtilitiesAmount_FullMethodName = "/base_amount.BaseAmountService/CalculateUtilitiesAmount"
	BaseAmountService_CalculateLeasingAmount_FullMethodName   = "/base_amount.BaseAmountService/CalculateLeasingAmount"
	BaseAmountService_ResetMobileBaseAmount_FullMethodName    = "/base_amount.BaseAmountService/ResetMobileBaseAmount"
	BaseAmountService_ResetUtilitiesBaseAmount_FullMethodName = "/base_amount.BaseAmountService/ResetUtilitiesBaseAmount"
	BaseAmountService_ResetLeasingBaseAmount_FullMethodName   = "/base_amount.BaseAmountService/ResetLeasingBaseAmount"
)

// BaseAmountServiceClient is the client API for BaseAmountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaseAmountServiceClient interface {
	GetBaseAmount(ctx context.Context, in *GetBaseAmountRequest, opts ...grpc.CallOption) (*GetBaseAmountResponse, error)
	CalculateMobileAmount(ctx context.Context, in *CalculateMobileAmountRequest, opts ...grpc.CallOption) (*CalculateMobileAmountResponse, error)
	CalculateUtilitiesAmount(ctx context.Context, in *CalculateUtilitiesAmountRequest, opts ...grpc.CallOption) (*CalculateUtilitiesAmountResponse, error)
	CalculateLeasingAmount(ctx context.Context, in *CalculateLeasingAmountRequest, opts ...grpc.CallOption) (*CalculateLeasingAmountResponse, error)
	ResetMobileBaseAmount(ctx context.Context, in *ResetMobileBaseAmountRequest, opts ...grpc.CallOption) (*ResetMobileBaseAmountResponse, error)
	ResetUtilitiesBaseAmount(ctx context.Context, in *ResetUtilitiesBaseAmountRequest, opts ...grpc.CallOption) (*ResetUtilitiesBaseAmountResponse, error)
	ResetLeasingBaseAmount(ctx context.Context, in *ResetLeasingBaseAmountRequest, opts ...grpc.CallOption) (*ResetLeasingBaseAmountResponse, error)
}

type baseAmountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseAmountServiceClient(cc grpc.ClientConnInterface) BaseAmountServiceClient {
	return &baseAmountServiceClient{cc}
}

func (c *baseAmountServiceClient) GetBaseAmount(ctx context.Context, in *GetBaseAmountRequest, opts ...grpc.CallOption) (*GetBaseAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBaseAmountResponse)
	err := c.cc.Invoke(ctx, BaseAmountService_GetBaseAmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseAmountServiceClient) CalculateMobileAmount(ctx context.Context, in *CalculateMobileAmountRequest, opts ...grpc.CallOption) (*CalculateMobileAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateMobileAmountResponse)
	err := c.cc.Invoke(ctx, BaseAmountService_CalculateMobileAmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseAmountServiceClient) CalculateUtilitiesAmount(ctx context.Context, in *CalculateUtilitiesAmountRequest, opts ...grpc.CallOption) (*CalculateUtilitiesAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateUtilitiesAmountResponse)
	err := c.cc.Invoke(ctx, BaseAmountService_CalculateUtilitiesAmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseAmountServiceClient) CalculateLeasingAmount(ctx context.Context, in *CalculateLeasingAmountRequest, opts ...grpc.CallOption) (*CalculateLeasingAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateLeasingAmountResponse)
	err := c.cc.Invoke(ctx, BaseAmountService_CalculateLeasingAmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseAmountServiceClient) ResetMobileBaseAmount(ctx context.Context, in *ResetMobileBaseAmountRequest, opts ...grpc.CallOption) (*ResetMobileBaseAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetMobileBaseAmountResponse)
	err := c.cc.Invoke(ctx, BaseAmountService_ResetMobileBaseAmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseAmountServiceClient) ResetUtilitiesBaseAmount(ctx context.Context, in *ResetUtilitiesBaseAmountRequest, opts ...grpc.CallOption) (*ResetUtilitiesBaseAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetUtilitiesBaseAmountResponse)
	err := c.cc.Invoke(ctx, BaseAmountService_ResetUtilitiesBaseAmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseAmountServiceClient) ResetLeasingBaseAmount(ctx context.Context, in *ResetLeasingBaseAmountRequest, opts ...grpc.CallOption) (*ResetLeasingBaseAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetLeasingBaseAmountResponse)
	err := c.cc.Invoke(ctx, BaseAmountService_ResetLeasingBaseAmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseAmountServiceServer is the server API for BaseAmountService service.
// All implementations must embed UnimplementedBaseAmountServiceServer
// for forward compatibility.
type BaseAmountServiceServer interface {
	GetBaseAmount(context.Context, *GetBaseAmountRequest) (*GetBaseAmountResponse, error)
	CalculateMobileAmount(context.Context, *CalculateMobileAmountRequest) (*CalculateMobileAmountResponse, error)
	CalculateUtilitiesAmount(context.Context, *CalculateUtilitiesAmountRequest) (*CalculateUtilitiesAmountResponse, error)
	CalculateLeasingAmount(context.Context, *CalculateLeasingAmountRequest) (*CalculateLeasingAmountResponse, error)
	ResetMobileBaseAmount(context.Context, *ResetMobileBaseAmountRequest) (*ResetMobileBaseAmountResponse, error)
	ResetUtilitiesBaseAmount(context.Context, *ResetUtilitiesBaseAmountRequest) (*ResetUtilitiesBaseAmountResponse, error)
	ResetLeasingBaseAmount(context.Context, *ResetLeasingBaseAmountRequest) (*ResetLeasingBaseAmountResponse, error)
	mustEmbedUnimplementedBaseAmountServiceServer()
}

// UnimplementedBaseAmountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBaseAmountServiceServer struct{}

func (UnimplementedBaseAmountServiceServer) GetBaseAmount(context.Context, *GetBaseAmountRequest) (*GetBaseAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBaseAmount not implemented")
}
func (UnimplementedBaseAmountServiceServer) CalculateMobileAmount(context.Context, *CalculateMobileAmountRequest) (*CalculateMobileAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateMobileAmount not implemented")
}
func (UnimplementedBaseAmountServiceServer) CalculateUtilitiesAmount(context.Context, *CalculateUtilitiesAmountRequest) (*CalculateUtilitiesAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateUtilitiesAmount not implemented")
}
func (UnimplementedBaseAmountServiceServer) CalculateLeasingAmount(context.Context, *CalculateLeasingAmountRequest) (*CalculateLeasingAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateLeasingAmount not implemented")
}
func (UnimplementedBaseAmountServiceServer) ResetMobileBaseAmount(context.Context, *ResetMobileBaseAmountRequest) (*ResetMobileBaseAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetMobileBaseAmount not implemented")
}
func (UnimplementedBaseAmountServiceServer) ResetUtilitiesBaseAmount(context.Context, *ResetUtilitiesBaseAmountRequest) (*ResetUtilitiesBaseAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetUtilitiesBaseAmount not implemented")
}
func (UnimplementedBaseAmountServiceServer) ResetLeasingBaseAmount(context.Context, *ResetLeasingBaseAmountRequest) (*ResetLeasingBaseAmountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetLeasingBaseAmount not implemented")
}
func (UnimplementedBaseAmountServiceServer) mustEmbedUnimplementedBaseAmountServiceServer() {}
func (UnimplementedBaseAmountServiceServer) testEmbeddedByValue()                           {}

// UnsafeBaseAmountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseAmountServiceServer will
// result in compilation errors.
type UnsafeBaseAmountServiceServer interface {
	mustEmbedUnimplementedBaseAmountServiceServer()
}

func RegisterBaseAmountServiceServer(s grpc.ServiceRegistrar, srv BaseAmountServiceServer) {
	// If the following call pancis, it indicates UnimplementedBaseAmountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BaseAmountService_ServiceDesc, srv)
}

func _BaseAmountService_GetBaseAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBaseAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseAmountServiceServer).GetBaseAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseAmountService_GetBaseAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseAmountServiceServer).GetBaseAmount(ctx, req.(*GetBaseAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseAmountService_CalculateMobileAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateMobileAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseAmountServiceServer).CalculateMobileAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseAmountService_CalculateMobileAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseAmountServiceServer).CalculateMobileAmount(ctx, req.(*CalculateMobileAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseAmountService_CalculateUtilitiesAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateUtilitiesAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseAmountServiceServer).CalculateUtilitiesAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseAmountService_CalculateUtilitiesAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseAmountServiceServer).CalculateUtilitiesAmount(ctx, req.(*CalculateUtilitiesAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseAmountService_CalculateLeasingAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateLeasingAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseAmountServiceServer).CalculateLeasingAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseAmountService_CalculateLeasingAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseAmountServiceServer).CalculateLeasingAmount(ctx, req.(*CalculateLeasingAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseAmountService_ResetMobileBaseAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetMobileBaseAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseAmountServiceServer).ResetMobileBaseAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseAmountService_ResetMobileBaseAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseAmountServiceServer).ResetMobileBaseAmount(ctx, req.(*ResetMobileBaseAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseAmountService_ResetUtilitiesBaseAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetUtilitiesBaseAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseAmountServiceServer).ResetUtilitiesBaseAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseAmountService_ResetUtilitiesBaseAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseAmountServiceServer).ResetUtilitiesBaseAmount(ctx, req.(*ResetUtilitiesBaseAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseAmountService_ResetLeasingBaseAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetLeasingBaseAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseAmountServiceServer).ResetLeasingBaseAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseAmountService_ResetLeasingBaseAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseAmountServiceServer).ResetLeasingBaseAmount(ctx, req.(*ResetLeasingBaseAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BaseAmountService_ServiceDesc is the grpc.ServiceDesc for BaseAmountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaseAmountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "base_amount.BaseAmountService",
	HandlerType: (*BaseAmountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBaseAmount",
			Handler:    _BaseAmountService_GetBaseAmount_Handler,
		},
		{
			MethodName: "CalculateMobileAmount",
			Handler:    _BaseAmountService_CalculateMobileAmount_Handler,
		},
		{
			MethodName: "CalculateUtilitiesAmount",
			Handler:    _BaseAmountService_CalculateUtilitiesAmount_Handler,
		},
		{
			MethodName: "CalculateLeasingAmount",
			Handler:    _BaseAmountService_CalculateLeasingAmount_Handler,
		},
		{
			MethodName: "ResetMobileBaseAmount",
			Handler:    _BaseAmountService_ResetMobileBaseAmount_Handler,
		},
		{
			MethodName: "ResetUtilitiesBaseAmount",
			Handler:    _BaseAmountService_ResetUtilitiesBaseAmount_Handler,
		},
		{
			MethodName: "ResetLeasingBaseAmount",
			Handler:    _BaseAmountService_ResetLeasingBaseAmount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base_amount.proto",
}
