// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: breakdown.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BreakdownService_CalculateRevenueBreakdown_FullMethodName  = "/breakdown.BreakdownService/CalculateRevenueBreakdown"
	BreakdownService_CalculateExpensesBreakdown_FullMethodName = "/breakdown.BreakdownService/CalculateExpensesBreakdown"
)

// BreakdownServiceClient is the client API for BreakdownService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BreakdownServiceClient interface {
	CalculateRevenueBreakdown(ctx context.Context, in *CalculateRevenueBreakdownRequest, opts ...grpc.CallOption) (*CalculateRevenueBreakdownResponse, error)
	CalculateExpensesBreakdown(ctx context.Context, in *CalculateExpensesBreakdownRequest, opts ...grpc.CallOption) (*CalculateExpensesBreakdownResponse, error)
}

type breakdownServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBreakdownServiceClient(cc grpc.ClientConnInterface) BreakdownServiceClient {
	return &breakdownServiceClient{cc}
}

func (c *breakdownServiceClient) CalculateRevenueBreakdown(ctx context.Context, in *CalculateRevenueBreakdownRequest, opts ...grpc.CallOption) (*CalculateRevenueBreakdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateRevenueBreakdownResponse)
	err := c.cc.Invoke(ctx, BreakdownService_CalculateRevenueBreakdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *breakdownServiceClient) CalculateExpensesBreakdown(ctx context.Context, in *CalculateExpensesBreakdownRequest, opts ...grpc.CallOption) (*CalculateExpensesBreakdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateExpensesBreakdownResponse)
	err := c.cc.Invoke(ctx, BreakdownService_CalculateExpensesBreakdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BreakdownServiceServer is the server API for BreakdownService service.
// All implementations must embed UnimplementedBreakdownServiceServer
// for forward compatibility.
type BreakdownServiceServer interface {
	CalculateRevenueBreakdown(context.Context, *CalculateRevenueBreakdownRequest) (*CalculateRevenueBreakdownResponse, error)
	CalculateExpensesBreakdown(context.Context, *CalculateExpensesBreakdownRequest) (*CalculateExpensesBreakdownResponse, error)
	mustEmbedUnimplementedBreakdownServiceServer()
}

// UnimplementedBreakdownServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBreakdownServiceServer struct{}

func (UnimplementedBreakdownServiceServer) CalculateRevenueBreakdown(context.Context, *CalculateRevenueBreakdownRequest) (*CalculateRevenueBreakdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateRevenueBreakdown not implemented")
}
func (UnimplementedBreakdownServiceServer) CalculateExpensesBreakdown(context.Context, *CalculateExpensesBreakdownRequest) (*CalculateExpensesBreakdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateExpensesBreakdown not implemented")
}
func (UnimplementedBreakdownServiceServer) mustEmbedUnimplementedBreakdownServiceServer() {}
func (UnimplementedBreakdownServiceServer) testEmbeddedByValue()                          {}

// UnsafeBreakdownServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BreakdownServiceServer will
// result in compilation errors.
type UnsafeBreakdownServiceServer interface {
	mustEmbedUnimplementedBreakdownServiceServer()
}

func RegisterBreakdownServiceServer(s grpc.ServiceRegistrar, srv BreakdownServiceServer) {
	// If the following call pancis, it indicates UnimplementedBreakdownServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BreakdownService_ServiceDesc, srv)
}

func _BreakdownService_CalculateRevenueBreakdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateRevenueBreakdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreakdownServiceServer).CalculateRevenueBreakdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BreakdownService_CalculateRevenueBreakdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreakdownServiceServer).CalculateRevenueBreakdown(ctx, req.(*CalculateRevenueBreakdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BreakdownService_CalculateExpensesBreakdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateExpensesBreakdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreakdownServiceServer).CalculateExpensesBreakdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BreakdownService_CalculateExpensesBreakdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreakdownServiceServer).CalculateExpensesBreakdown(ctx, req.(*CalculateExpensesBreakdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BreakdownService_ServiceDesc is the grpc.ServiceDesc for BreakdownService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BreakdownService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "breakdown.BreakdownService",
	HandlerType: (*BreakdownServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateRevenueBreakdown",
			Handler:    _BreakdownService_CalculateRevenueBreakdown_Handler,
		},
		{
			MethodName: "CalculateExpensesBreakdown",
			Handler:    _BreakdownService_CalculateExpensesBreakdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "breakdown.proto",
}
