// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: breakdown.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateRevenueBreakdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateRevenueBreakdownRequest) Reset() {
	*x = CalculateRevenueBreakdownRequest{}
	mi := &file_breakdown_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRevenueBreakdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRevenueBreakdownRequest) ProtoMessage() {}

func (x *CalculateRevenueBreakdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breakdown_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRevenueBreakdownRequest.ProtoReflect.Descriptor instead.
func (*CalculateRevenueBreakdownRequest) Descriptor() ([]byte, []int) {
	return file_breakdown_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateRevenueBreakdownRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CalculateRevenueBreakdownResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RevenueBreakdown *RevenueBreakdown      `protobuf:"bytes,2,opt,name=revenue_breakdown,json=revenueBreakdown,proto3" json:"revenue_breakdown,omitempty"`
	Code             int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CalculateRevenueBreakdownResponse) Reset() {
	*x = CalculateRevenueBreakdownResponse{}
	mi := &file_breakdown_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRevenueBreakdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRevenueBreakdownResponse) ProtoMessage() {}

func (x *CalculateRevenueBreakdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_breakdown_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRevenueBreakdownResponse.ProtoReflect.Descriptor instead.
func (*CalculateRevenueBreakdownResponse) Descriptor() ([]byte, []int) {
	return file_breakdown_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateRevenueBreakdownResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CalculateRevenueBreakdownResponse) GetRevenueBreakdown() *RevenueBreakdown {
	if x != nil {
		return x.RevenueBreakdown
	}
	return nil
}

func (x *CalculateRevenueBreakdownResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type CalculateExpensesBreakdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateExpensesBreakdownRequest) Reset() {
	*x = CalculateExpensesBreakdownRequest{}
	mi := &file_breakdown_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateExpensesBreakdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateExpensesBreakdownRequest) ProtoMessage() {}

func (x *CalculateExpensesBreakdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breakdown_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateExpensesBreakdownRequest.ProtoReflect.Descriptor instead.
func (*CalculateExpensesBreakdownRequest) Descriptor() ([]byte, []int) {
	return file_breakdown_proto_rawDescGZIP(), []int{2}
}

func (x *CalculateExpensesBreakdownRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CalculateExpensesBreakdownResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestId         string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ExpensesBreakdown *ExpensesBreakdown     `protobuf:"bytes,2,opt,name=expenses_breakdown,json=expensesBreakdown,proto3" json:"expenses_breakdown,omitempty"`
	Code              int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CalculateExpensesBreakdownResponse) Reset() {
	*x = CalculateExpensesBreakdownResponse{}
	mi := &file_breakdown_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateExpensesBreakdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateExpensesBreakdownResponse) ProtoMessage() {}

func (x *CalculateExpensesBreakdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_breakdown_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateExpensesBreakdownResponse.ProtoReflect.Descriptor instead.
func (*CalculateExpensesBreakdownResponse) Descriptor() ([]byte, []int) {
	return file_breakdown_proto_rawDescGZIP(), []int{3}
}

func (x *CalculateExpensesBreakdownResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CalculateExpensesBreakdownResponse) GetExpensesBreakdown() *ExpensesBreakdown {
	if x != nil {
		return x.ExpensesBreakdown
	}
	return nil
}

func (x *CalculateExpensesBreakdownResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_breakdown_proto protoreflect.FileDescriptor

const file_breakdown_proto_rawDesc = "" +
	"\n" +
	"\x0fbreakdown.proto\x12\tbreakdown\x1a\fcommon.proto\"A\n" +
	" CalculateRevenueBreakdownRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\x9d\x01\n" +
	"!CalculateRevenueBreakdownResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12E\n" +
	"\x11revenue_breakdown\x18\x02 \x01(\v2\x18.common.RevenueBreakdownR\x10revenueBreakdown\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\"B\n" +
	"!CalculateExpensesBreakdownRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xa1\x01\n" +
	"\"CalculateExpensesBreakdownResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12H\n" +
	"\x12expenses_breakdown\x18\x02 \x01(\v2\x19.common.ExpensesBreakdownR\x11expensesBreakdown\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code2\x85\x02\n" +
	"\x10BreakdownService\x12v\n" +
	"\x19CalculateRevenueBreakdown\x12+.breakdown.CalculateRevenueBreakdownRequest\x1a,.breakdown.CalculateRevenueBreakdownResponse\x12y\n" +
	"\x1aCalculateExpensesBreakdown\x12,.breakdown.CalculateExpensesBreakdownRequest\x1a-.breakdown.CalculateExpensesBreakdownResponseB/Z-github.com/IbadT/business_bank_back/pkg/protob\x06proto3"

var (
	file_breakdown_proto_rawDescOnce sync.Once
	file_breakdown_proto_rawDescData []byte
)

func file_breakdown_proto_rawDescGZIP() []byte {
	file_breakdown_proto_rawDescOnce.Do(func() {
		file_breakdown_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_breakdown_proto_rawDesc), len(file_breakdown_proto_rawDesc)))
	})
	return file_breakdown_proto_rawDescData
}

var file_breakdown_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_breakdown_proto_goTypes = []any{
	(*CalculateRevenueBreakdownRequest)(nil),   // 0: breakdown.CalculateRevenueBreakdownRequest
	(*CalculateRevenueBreakdownResponse)(nil),  // 1: breakdown.CalculateRevenueBreakdownResponse
	(*CalculateExpensesBreakdownRequest)(nil),  // 2: breakdown.CalculateExpensesBreakdownRequest
	(*CalculateExpensesBreakdownResponse)(nil), // 3: breakdown.CalculateExpensesBreakdownResponse
	(*RevenueBreakdown)(nil),                   // 4: common.RevenueBreakdown
	(*ExpensesBreakdown)(nil),                  // 5: common.ExpensesBreakdown
}
var file_breakdown_proto_depIdxs = []int32{
	4, // 0: breakdown.CalculateRevenueBreakdownResponse.revenue_breakdown:type_name -> common.RevenueBreakdown
	5, // 1: breakdown.CalculateExpensesBreakdownResponse.expenses_breakdown:type_name -> common.ExpensesBreakdown
	0, // 2: breakdown.BreakdownService.CalculateRevenueBreakdown:input_type -> breakdown.CalculateRevenueBreakdownRequest
	2, // 3: breakdown.BreakdownService.CalculateExpensesBreakdown:input_type -> breakdown.CalculateExpensesBreakdownRequest
	1, // 4: breakdown.BreakdownService.CalculateRevenueBreakdown:output_type -> breakdown.CalculateRevenueBreakdownResponse
	3, // 5: breakdown.BreakdownService.CalculateExpensesBreakdown:output_type -> breakdown.CalculateExpensesBreakdownResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_breakdown_proto_init() }
func file_breakdown_proto_init() {
	if File_breakdown_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_breakdown_proto_rawDesc), len(file_breakdown_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_breakdown_proto_goTypes,
		DependencyIndexes: file_breakdown_proto_depIdxs,
		MessageInfos:      file_breakdown_proto_msgTypes,
	}.Build()
	File_breakdown_proto = out.File
	file_breakdown_proto_goTypes = nil
	file_breakdown_proto_depIdxs = nil
}
