// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GeneratedTransaction with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GeneratedTransaction) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GeneratedTransaction with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GeneratedTransactionMultiError, or nil if none found.
func (m *GeneratedTransaction) ValidateAll() error {
	return m.validate(true)
}

func (m *GeneratedTransaction) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for RequestId

	// no validation rules for TransactionId

	// no validation rules for TransactionDate

	// no validation rules for PostingDate

	// no validation rules for Type

	// no validation rules for Category

	// no validation rules for Method

	// no validation rules for Amount

	// no validation rules for BalanceAfter

	// no validation rules for IsManual

	// no validation rules for SortOrder

	// no validation rules for CalculationDetails

	if len(errors) > 0 {
		return GeneratedTransactionMultiError(errors)
	}

	return nil
}

// GeneratedTransactionMultiError is an error wrapping multiple validation
// errors returned by GeneratedTransaction.ValidateAll() if the designated
// constraints aren't met.
type GeneratedTransactionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GeneratedTransactionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GeneratedTransactionMultiError) AllErrors() []error { return m }

// GeneratedTransactionValidationError is the validation error returned by
// GeneratedTransaction.Validate if the designated constraints aren't met.
type GeneratedTransactionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GeneratedTransactionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GeneratedTransactionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GeneratedTransactionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GeneratedTransactionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GeneratedTransactionValidationError) ErrorName() string {
	return "GeneratedTransactionValidationError"
}

// Error satisfies the builtin error interface
func (e GeneratedTransactionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGeneratedTransaction.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GeneratedTransactionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GeneratedTransactionValidationError{}

// Validate checks the field values on RevenueBreakdown with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RevenueBreakdown) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RevenueBreakdown with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RevenueBreakdownMultiError, or nil if none found.
func (m *RevenueBreakdown) ValidateAll() error {
	return m.validate(true)
}

func (m *RevenueBreakdown) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TotalAch

	// no validation rules for TotalWire

	// no validation rules for TotalZelle

	// no validation rules for TotalGateway

	// no validation rules for TotalOther

	if len(errors) > 0 {
		return RevenueBreakdownMultiError(errors)
	}

	return nil
}

// RevenueBreakdownMultiError is an error wrapping multiple validation errors
// returned by RevenueBreakdown.ValidateAll() if the designated constraints
// aren't met.
type RevenueBreakdownMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RevenueBreakdownMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RevenueBreakdownMultiError) AllErrors() []error { return m }

// RevenueBreakdownValidationError is the validation error returned by
// RevenueBreakdown.Validate if the designated constraints aren't met.
type RevenueBreakdownValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RevenueBreakdownValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RevenueBreakdownValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RevenueBreakdownValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RevenueBreakdownValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RevenueBreakdownValidationError) ErrorName() string { return "RevenueBreakdownValidationError" }

// Error satisfies the builtin error interface
func (e RevenueBreakdownValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRevenueBreakdown.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RevenueBreakdownValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RevenueBreakdownValidationError{}

// Validate checks the field values on ExpensesBreakdown with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ExpensesBreakdown) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ExpensesBreakdown with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ExpensesBreakdownMultiError, or nil if none found.
func (m *ExpensesBreakdown) ValidateAll() error {
	return m.validate(true)
}

func (m *ExpensesBreakdown) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ByCard

	// no validation rules for ByAccount

	if len(errors) > 0 {
		return ExpensesBreakdownMultiError(errors)
	}

	return nil
}

// ExpensesBreakdownMultiError is an error wrapping multiple validation errors
// returned by ExpensesBreakdown.ValidateAll() if the designated constraints
// aren't met.
type ExpensesBreakdownMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExpensesBreakdownMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExpensesBreakdownMultiError) AllErrors() []error { return m }

// ExpensesBreakdownValidationError is the validation error returned by
// ExpensesBreakdown.Validate if the designated constraints aren't met.
type ExpensesBreakdownValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExpensesBreakdownValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExpensesBreakdownValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExpensesBreakdownValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExpensesBreakdownValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExpensesBreakdownValidationError) ErrorName() string {
	return "ExpensesBreakdownValidationError"
}

// Error satisfies the builtin error interface
func (e ExpensesBreakdownValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExpensesBreakdown.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExpensesBreakdownValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExpensesBreakdownValidationError{}
