// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GeneratedTransaction - общий тип транзакции
type GeneratedTransaction struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestId          string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TransactionId      string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	TransactionDate    string                 `protobuf:"bytes,4,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"`
	PostingDate        string                 `protobuf:"bytes,5,opt,name=posting_date,json=postingDate,proto3" json:"posting_date,omitempty"`
	Type               string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Category           string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	Method             string                 `protobuf:"bytes,8,opt,name=method,proto3" json:"method,omitempty"`
	Amount             float64                `protobuf:"fixed64,9,opt,name=amount,proto3" json:"amount,omitempty"`
	BalanceAfter       float64                `protobuf:"fixed64,10,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	IsManual           bool                   `protobuf:"varint,11,opt,name=is_manual,json=isManual,proto3" json:"is_manual,omitempty"`
	SortOrder          int32                  `protobuf:"varint,12,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	CalculationDetails map[string]string      `protobuf:"bytes,13,rep,name=calculation_details,json=calculationDetails,proto3" json:"calculation_details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GeneratedTransaction) Reset() {
	*x = GeneratedTransaction{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedTransaction) ProtoMessage() {}

func (x *GeneratedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedTransaction.ProtoReflect.Descriptor instead.
func (*GeneratedTransaction) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratedTransaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GeneratedTransaction) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GeneratedTransaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *GeneratedTransaction) GetTransactionDate() string {
	if x != nil {
		return x.TransactionDate
	}
	return ""
}

func (x *GeneratedTransaction) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

func (x *GeneratedTransaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GeneratedTransaction) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GeneratedTransaction) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *GeneratedTransaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GeneratedTransaction) GetBalanceAfter() float64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *GeneratedTransaction) GetIsManual() bool {
	if x != nil {
		return x.IsManual
	}
	return false
}

func (x *GeneratedTransaction) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *GeneratedTransaction) GetCalculationDetails() map[string]string {
	if x != nil {
		return x.CalculationDetails
	}
	return nil
}

// RevenueBreakdown - разбивка доходов
type RevenueBreakdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalAch      float64                `protobuf:"fixed64,1,opt,name=total_ach,json=totalAch,proto3" json:"total_ach,omitempty"`
	TotalWire     float64                `protobuf:"fixed64,2,opt,name=total_wire,json=totalWire,proto3" json:"total_wire,omitempty"`
	TotalZelle    float64                `protobuf:"fixed64,3,opt,name=total_zelle,json=totalZelle,proto3" json:"total_zelle,omitempty"`
	TotalGateway  float64                `protobuf:"fixed64,4,opt,name=total_gateway,json=totalGateway,proto3" json:"total_gateway,omitempty"`
	TotalOther    float64                `protobuf:"fixed64,5,opt,name=total_other,json=totalOther,proto3" json:"total_other,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevenueBreakdown) Reset() {
	*x = RevenueBreakdown{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevenueBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevenueBreakdown) ProtoMessage() {}

func (x *RevenueBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevenueBreakdown.ProtoReflect.Descriptor instead.
func (*RevenueBreakdown) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *RevenueBreakdown) GetTotalAch() float64 {
	if x != nil {
		return x.TotalAch
	}
	return 0
}

func (x *RevenueBreakdown) GetTotalWire() float64 {
	if x != nil {
		return x.TotalWire
	}
	return 0
}

func (x *RevenueBreakdown) GetTotalZelle() float64 {
	if x != nil {
		return x.TotalZelle
	}
	return 0
}

func (x *RevenueBreakdown) GetTotalGateway() float64 {
	if x != nil {
		return x.TotalGateway
	}
	return 0
}

func (x *RevenueBreakdown) GetTotalOther() float64 {
	if x != nil {
		return x.TotalOther
	}
	return 0
}

// ExpensesBreakdown - разбивка расходов
type ExpensesBreakdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ByCard        float64                `protobuf:"fixed64,1,opt,name=by_card,json=byCard,proto3" json:"by_card,omitempty"`
	ByAccount     float64                `protobuf:"fixed64,2,opt,name=by_account,json=byAccount,proto3" json:"by_account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpensesBreakdown) Reset() {
	*x = ExpensesBreakdown{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpensesBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpensesBreakdown) ProtoMessage() {}

func (x *ExpensesBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpensesBreakdown.ProtoReflect.Descriptor instead.
func (*ExpensesBreakdown) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *ExpensesBreakdown) GetByCard() float64 {
	if x != nil {
		return x.ByCard
	}
	return 0
}

func (x *ExpensesBreakdown) GetByAccount() float64 {
	if x != nil {
		return x.ByAccount
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x06common\"\xa9\x04\n" +
	"\x14GeneratedTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12)\n" +
	"\x10transaction_date\x18\x04 \x01(\tR\x0ftransactionDate\x12!\n" +
	"\fposting_date\x18\x05 \x01(\tR\vpostingDate\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12\x16\n" +
	"\x06method\x18\b \x01(\tR\x06method\x12\x16\n" +
	"\x06amount\x18\t \x01(\x01R\x06amount\x12#\n" +
	"\rbalance_after\x18\n" +
	" \x01(\x01R\fbalanceAfter\x12\x1b\n" +
	"\tis_manual\x18\v \x01(\bR\bisManual\x12\x1d\n" +
	"\n" +
	"sort_order\x18\f \x01(\x05R\tsortOrder\x12e\n" +
	"\x13calculation_details\x18\r \x03(\v24.common.GeneratedTransaction.CalculationDetailsEntryR\x12calculationDetails\x1aE\n" +
	"\x17CalculationDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x01\n" +
	"\x10RevenueBreakdown\x12\x1b\n" +
	"\ttotal_ach\x18\x01 \x01(\x01R\btotalAch\x12\x1d\n" +
	"\n" +
	"total_wire\x18\x02 \x01(\x01R\ttotalWire\x12\x1f\n" +
	"\vtotal_zelle\x18\x03 \x01(\x01R\n" +
	"totalZelle\x12#\n" +
	"\rtotal_gateway\x18\x04 \x01(\x01R\ftotalGateway\x12\x1f\n" +
	"\vtotal_other\x18\x05 \x01(\x01R\n" +
	"totalOther\"K\n" +
	"\x11ExpensesBreakdown\x12\x17\n" +
	"\aby_card\x18\x01 \x01(\x01R\x06byCard\x12\x1d\n" +
	"\n" +
	"by_account\x18\x02 \x01(\x01R\tbyAccountB/Z-github.com/IbadT/business_bank_back/pkg/protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_proto_goTypes = []any{
	(*GeneratedTransaction)(nil), // 0: common.GeneratedTransaction
	(*RevenueBreakdown)(nil),     // 1: common.RevenueBreakdown
	(*ExpensesBreakdown)(nil),    // 2: common.ExpensesBreakdown
	nil,                          // 3: common.GeneratedTransaction.CalculationDetailsEntry
}
var file_common_proto_depIdxs = []int32{
	3, // 0: common.GeneratedTransaction.calculation_details:type_name -> common.GeneratedTransaction.CalculationDetailsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
