// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gateway struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gateway) Reset() {
	*x = Gateway{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gateway) ProtoMessage() {}

func (x *Gateway) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gateway.ProtoReflect.Descriptor instead.
func (*Gateway) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *Gateway) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Gateway) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetB2CGatewaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetB2CGatewaysRequest) Reset() {
	*x = GetB2CGatewaysRequest{}
	mi := &file_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetB2CGatewaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetB2CGatewaysRequest) ProtoMessage() {}

func (x *GetB2CGatewaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetB2CGatewaysRequest.ProtoReflect.Descriptor instead.
func (*GetB2CGatewaysRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

type GetB2CGatewaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateway       *Gateway               `protobuf:"bytes,1,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetB2CGatewaysResponse) Reset() {
	*x = GetB2CGatewaysResponse{}
	mi := &file_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetB2CGatewaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetB2CGatewaysResponse) ProtoMessage() {}

func (x *GetB2CGatewaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetB2CGatewaysResponse.ProtoReflect.Descriptor instead.
func (*GetB2CGatewaysResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *GetB2CGatewaysResponse) GetGateway() *Gateway {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *GetB2CGatewaysResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type UpdateB2CGatewaysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_id from cookie
	GatewayId     string `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateB2CGatewaysRequest) Reset() {
	*x = UpdateB2CGatewaysRequest{}
	mi := &file_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateB2CGatewaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateB2CGatewaysRequest) ProtoMessage() {}

func (x *UpdateB2CGatewaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateB2CGatewaysRequest.ProtoReflect.Descriptor instead.
func (*UpdateB2CGatewaysRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateB2CGatewaysRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

type UpdateB2CGatewaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateB2CGatewaysResponse) Reset() {
	*x = UpdateB2CGatewaysResponse{}
	mi := &file_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateB2CGatewaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateB2CGatewaysResponse) ProtoMessage() {}

func (x *UpdateB2CGatewaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateB2CGatewaysResponse.ProtoReflect.Descriptor instead.
func (*UpdateB2CGatewaysResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateB2CGatewaysResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateB2CGatewaysResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type DeleteB2CGatewaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteB2CGatewaysRequest) Reset() {
	*x = DeleteB2CGatewaysRequest{}
	mi := &file_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteB2CGatewaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteB2CGatewaysRequest) ProtoMessage() {}

func (x *DeleteB2CGatewaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteB2CGatewaysRequest.ProtoReflect.Descriptor instead.
func (*DeleteB2CGatewaysRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{5}
}

type DeleteB2CGatewaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteB2CGatewaysResponse) Reset() {
	*x = DeleteB2CGatewaysResponse{}
	mi := &file_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteB2CGatewaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteB2CGatewaysResponse) ProtoMessage() {}

func (x *DeleteB2CGatewaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteB2CGatewaysResponse.ProtoReflect.Descriptor instead.
func (*DeleteB2CGatewaysResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteB2CGatewaysResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteB2CGatewaysResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\x12\agateway\"-\n" +
	"\aGateway\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x17\n" +
	"\x15GetB2CGatewaysRequest\"X\n" +
	"\x16GetB2CGatewaysResponse\x12*\n" +
	"\agateway\x18\x01 \x01(\v2\x10.gateway.GatewayR\agateway\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"9\n" +
	"\x18UpdateB2CGatewaysRequest\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\"I\n" +
	"\x19UpdateB2CGatewaysResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"\x1a\n" +
	"\x18DeleteB2CGatewaysRequest\"I\n" +
	"\x19DeleteB2CGatewaysResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code2\x9b\x02\n" +
	"\x0eGatewayService\x12Q\n" +
	"\x0eGetB2CGateways\x12\x1e.gateway.GetB2CGatewaysRequest\x1a\x1f.gateway.GetB2CGatewaysResponse\x12Z\n" +
	"\x11UpdateB2CGateways\x12!.gateway.UpdateB2CGatewaysRequest\x1a\".gateway.UpdateB2CGatewaysResponse\x12Z\n" +
	"\x11DeleteB2CGateways\x12!.gateway.DeleteB2CGatewaysRequest\x1a\".gateway.DeleteB2CGatewaysResponseB/Z-github.com/IbadT/business_bank_back/pkg/protob\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gateway_proto_goTypes = []any{
	(*Gateway)(nil),                   // 0: gateway.Gateway
	(*GetB2CGatewaysRequest)(nil),     // 1: gateway.GetB2CGatewaysRequest
	(*GetB2CGatewaysResponse)(nil),    // 2: gateway.GetB2CGatewaysResponse
	(*UpdateB2CGatewaysRequest)(nil),  // 3: gateway.UpdateB2CGatewaysRequest
	(*UpdateB2CGatewaysResponse)(nil), // 4: gateway.UpdateB2CGatewaysResponse
	(*DeleteB2CGatewaysRequest)(nil),  // 5: gateway.DeleteB2CGatewaysRequest
	(*DeleteB2CGatewaysResponse)(nil), // 6: gateway.DeleteB2CGatewaysResponse
}
var file_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.GetB2CGatewaysResponse.gateway:type_name -> gateway.Gateway
	1, // 1: gateway.GatewayService.GetB2CGateways:input_type -> gateway.GetB2CGatewaysRequest
	3, // 2: gateway.GatewayService.UpdateB2CGateways:input_type -> gateway.UpdateB2CGatewaysRequest
	5, // 3: gateway.GatewayService.DeleteB2CGateways:input_type -> gateway.DeleteB2CGatewaysRequest
	2, // 4: gateway.GatewayService.GetB2CGateways:output_type -> gateway.GetB2CGatewaysResponse
	4, // 5: gateway.GatewayService.UpdateB2CGateways:output_type -> gateway.UpdateB2CGatewaysResponse
	6, // 6: gateway.GatewayService.DeleteB2CGateways:output_type -> gateway.DeleteB2CGatewaysResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
