// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: gateway.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Gateway with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Gateway) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Gateway with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in GatewayMultiError, or nil if none found.
func (m *Gateway) ValidateAll() error {
	return m.validate(true)
}

func (m *Gateway) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if len(errors) > 0 {
		return GatewayMultiError(errors)
	}

	return nil
}

// GatewayMultiError is an error wrapping multiple validation errors returned
// by Gateway.ValidateAll() if the designated constraints aren't met.
type GatewayMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GatewayMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GatewayMultiError) AllErrors() []error { return m }

// GatewayValidationError is the validation error returned by Gateway.Validate
// if the designated constraints aren't met.
type GatewayValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GatewayValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GatewayValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GatewayValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GatewayValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GatewayValidationError) ErrorName() string { return "GatewayValidationError" }

// Error satisfies the builtin error interface
func (e GatewayValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGateway.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GatewayValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GatewayValidationError{}

// Validate checks the field values on GetB2CGatewaysRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetB2CGatewaysRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetB2CGatewaysRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetB2CGatewaysRequestMultiError, or nil if none found.
func (m *GetB2CGatewaysRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetB2CGatewaysRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetB2CGatewaysRequestMultiError(errors)
	}

	return nil
}

// GetB2CGatewaysRequestMultiError is an error wrapping multiple validation
// errors returned by GetB2CGatewaysRequest.ValidateAll() if the designated
// constraints aren't met.
type GetB2CGatewaysRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetB2CGatewaysRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetB2CGatewaysRequestMultiError) AllErrors() []error { return m }

// GetB2CGatewaysRequestValidationError is the validation error returned by
// GetB2CGatewaysRequest.Validate if the designated constraints aren't met.
type GetB2CGatewaysRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetB2CGatewaysRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetB2CGatewaysRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetB2CGatewaysRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetB2CGatewaysRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetB2CGatewaysRequestValidationError) ErrorName() string {
	return "GetB2CGatewaysRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetB2CGatewaysRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetB2CGatewaysRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetB2CGatewaysRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetB2CGatewaysRequestValidationError{}

// Validate checks the field values on GetB2CGatewaysResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetB2CGatewaysResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetB2CGatewaysResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetB2CGatewaysResponseMultiError, or nil if none found.
func (m *GetB2CGatewaysResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetB2CGatewaysResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetGateway()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetB2CGatewaysResponseValidationError{
					field:  "Gateway",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetB2CGatewaysResponseValidationError{
					field:  "Gateway",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGateway()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetB2CGatewaysResponseValidationError{
				field:  "Gateway",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Code

	if len(errors) > 0 {
		return GetB2CGatewaysResponseMultiError(errors)
	}

	return nil
}

// GetB2CGatewaysResponseMultiError is an error wrapping multiple validation
// errors returned by GetB2CGatewaysResponse.ValidateAll() if the designated
// constraints aren't met.
type GetB2CGatewaysResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetB2CGatewaysResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetB2CGatewaysResponseMultiError) AllErrors() []error { return m }

// GetB2CGatewaysResponseValidationError is the validation error returned by
// GetB2CGatewaysResponse.Validate if the designated constraints aren't met.
type GetB2CGatewaysResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetB2CGatewaysResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetB2CGatewaysResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetB2CGatewaysResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetB2CGatewaysResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetB2CGatewaysResponseValidationError) ErrorName() string {
	return "GetB2CGatewaysResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetB2CGatewaysResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetB2CGatewaysResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetB2CGatewaysResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetB2CGatewaysResponseValidationError{}

// Validate checks the field values on UpdateB2CGatewaysRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateB2CGatewaysRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateB2CGatewaysRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateB2CGatewaysRequestMultiError, or nil if none found.
func (m *UpdateB2CGatewaysRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateB2CGatewaysRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetGatewayId() != "" {

	}

	if len(errors) > 0 {
		return UpdateB2CGatewaysRequestMultiError(errors)
	}

	return nil
}

// UpdateB2CGatewaysRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateB2CGatewaysRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateB2CGatewaysRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateB2CGatewaysRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateB2CGatewaysRequestMultiError) AllErrors() []error { return m }

// UpdateB2CGatewaysRequestValidationError is the validation error returned by
// UpdateB2CGatewaysRequest.Validate if the designated constraints aren't met.
type UpdateB2CGatewaysRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateB2CGatewaysRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateB2CGatewaysRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateB2CGatewaysRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateB2CGatewaysRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateB2CGatewaysRequestValidationError) ErrorName() string {
	return "UpdateB2CGatewaysRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateB2CGatewaysRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateB2CGatewaysRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateB2CGatewaysRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateB2CGatewaysRequestValidationError{}

// Validate checks the field values on UpdateB2CGatewaysResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateB2CGatewaysResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateB2CGatewaysResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateB2CGatewaysResponseMultiError, or nil if none found.
func (m *UpdateB2CGatewaysResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateB2CGatewaysResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	// no validation rules for Code

	if len(errors) > 0 {
		return UpdateB2CGatewaysResponseMultiError(errors)
	}

	return nil
}

// UpdateB2CGatewaysResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateB2CGatewaysResponse.ValidateAll() if the
// designated constraints aren't met.
type UpdateB2CGatewaysResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateB2CGatewaysResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateB2CGatewaysResponseMultiError) AllErrors() []error { return m }

// UpdateB2CGatewaysResponseValidationError is the validation error returned by
// UpdateB2CGatewaysResponse.Validate if the designated constraints aren't met.
type UpdateB2CGatewaysResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateB2CGatewaysResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateB2CGatewaysResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateB2CGatewaysResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateB2CGatewaysResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateB2CGatewaysResponseValidationError) ErrorName() string {
	return "UpdateB2CGatewaysResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateB2CGatewaysResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateB2CGatewaysResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateB2CGatewaysResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateB2CGatewaysResponseValidationError{}

// Validate checks the field values on DeleteB2CGatewaysRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteB2CGatewaysRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteB2CGatewaysRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteB2CGatewaysRequestMultiError, or nil if none found.
func (m *DeleteB2CGatewaysRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteB2CGatewaysRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteB2CGatewaysRequestMultiError(errors)
	}

	return nil
}

// DeleteB2CGatewaysRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteB2CGatewaysRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteB2CGatewaysRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteB2CGatewaysRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteB2CGatewaysRequestMultiError) AllErrors() []error { return m }

// DeleteB2CGatewaysRequestValidationError is the validation error returned by
// DeleteB2CGatewaysRequest.Validate if the designated constraints aren't met.
type DeleteB2CGatewaysRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteB2CGatewaysRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteB2CGatewaysRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteB2CGatewaysRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteB2CGatewaysRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteB2CGatewaysRequestValidationError) ErrorName() string {
	return "DeleteB2CGatewaysRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteB2CGatewaysRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteB2CGatewaysRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteB2CGatewaysRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteB2CGatewaysRequestValidationError{}

// Validate checks the field values on DeleteB2CGatewaysResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteB2CGatewaysResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteB2CGatewaysResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteB2CGatewaysResponseMultiError, or nil if none found.
func (m *DeleteB2CGatewaysResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteB2CGatewaysResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	// no validation rules for Code

	if len(errors) > 0 {
		return DeleteB2CGatewaysResponseMultiError(errors)
	}

	return nil
}

// DeleteB2CGatewaysResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteB2CGatewaysResponse.ValidateAll() if the
// designated constraints aren't met.
type DeleteB2CGatewaysResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteB2CGatewaysResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteB2CGatewaysResponseMultiError) AllErrors() []error { return m }

// DeleteB2CGatewaysResponseValidationError is the validation error returned by
// DeleteB2CGatewaysResponse.Validate if the designated constraints aren't met.
type DeleteB2CGatewaysResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteB2CGatewaysResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteB2CGatewaysResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteB2CGatewaysResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteB2CGatewaysResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteB2CGatewaysResponseValidationError) ErrorName() string {
	return "DeleteB2CGatewaysResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteB2CGatewaysResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteB2CGatewaysResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteB2CGatewaysResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteB2CGatewaysResponseValidationError{}
