// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: gateway.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_GetB2CGateways_FullMethodName    = "/gateway.GatewayService/GetB2CGateways"
	GatewayService_UpdateB2CGateways_FullMethodName = "/gateway.GatewayService/UpdateB2CGateways"
	GatewayService_DeleteB2CGateways_FullMethodName = "/gateway.GatewayService/DeleteB2CGateways"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	GetB2CGateways(ctx context.Context, in *GetB2CGatewaysRequest, opts ...grpc.CallOption) (*GetB2CGatewaysResponse, error)
	UpdateB2CGateways(ctx context.Context, in *UpdateB2CGatewaysRequest, opts ...grpc.CallOption) (*UpdateB2CGatewaysResponse, error)
	DeleteB2CGateways(ctx context.Context, in *DeleteB2CGatewaysRequest, opts ...grpc.CallOption) (*DeleteB2CGatewaysResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) GetB2CGateways(ctx context.Context, in *GetB2CGatewaysRequest, opts ...grpc.CallOption) (*GetB2CGatewaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetB2CGatewaysResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetB2CGateways_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) UpdateB2CGateways(ctx context.Context, in *UpdateB2CGatewaysRequest, opts ...grpc.CallOption) (*UpdateB2CGatewaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateB2CGatewaysResponse)
	err := c.cc.Invoke(ctx, GatewayService_UpdateB2CGateways_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) DeleteB2CGateways(ctx context.Context, in *DeleteB2CGatewaysRequest, opts ...grpc.CallOption) (*DeleteB2CGatewaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteB2CGatewaysResponse)
	err := c.cc.Invoke(ctx, GatewayService_DeleteB2CGateways_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
type GatewayServiceServer interface {
	GetB2CGateways(context.Context, *GetB2CGatewaysRequest) (*GetB2CGatewaysResponse, error)
	UpdateB2CGateways(context.Context, *UpdateB2CGatewaysRequest) (*UpdateB2CGatewaysResponse, error)
	DeleteB2CGateways(context.Context, *DeleteB2CGatewaysRequest) (*DeleteB2CGatewaysResponse, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) GetB2CGateways(context.Context, *GetB2CGatewaysRequest) (*GetB2CGatewaysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetB2CGateways not implemented")
}
func (UnimplementedGatewayServiceServer) UpdateB2CGateways(context.Context, *UpdateB2CGatewaysRequest) (*UpdateB2CGatewaysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateB2CGateways not implemented")
}
func (UnimplementedGatewayServiceServer) DeleteB2CGateways(context.Context, *DeleteB2CGatewaysRequest) (*DeleteB2CGatewaysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteB2CGateways not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call pancis, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_GetB2CGateways_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetB2CGatewaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetB2CGateways(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetB2CGateways_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetB2CGateways(ctx, req.(*GetB2CGatewaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_UpdateB2CGateways_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateB2CGatewaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).UpdateB2CGateways(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_UpdateB2CGateways_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).UpdateB2CGateways(ctx, req.(*UpdateB2CGatewaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_DeleteB2CGateways_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteB2CGatewaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).DeleteB2CGateways(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_DeleteB2CGateways_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).DeleteB2CGateways(ctx, req.(*DeleteB2CGatewaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetB2CGateways",
			Handler:    _GatewayService_GetB2CGateways_Handler,
		},
		{
			MethodName: "UpdateB2CGateways",
			Handler:    _GatewayService_UpdateB2CGateways_Handler,
		},
		{
			MethodName: "DeleteB2CGateways",
			Handler:    _GatewayService_DeleteB2CGateways_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
