// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: generate.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GenerateRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GenerateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenerateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GenerateRequestMultiError, or nil if none found.
func (m *GenerateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GenerateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if val := m.GetMonth(); val < 1 || val > 12 {
		err := GenerateRequestValidationError{
			field:  "Month",
			reason: "value must be inside range [1, 12]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetYear(); val < 2000 || val > 2100 {
		err := GenerateRequestValidationError{
			field:  "Year",
			reason: "value must be inside range [2000, 2100]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetTurnover() <= 0 {
		err := GenerateRequestValidationError{
			field:  "Turnover",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetDesiredProfitPercent(); val < 0 || val > 100 {
		err := GenerateRequestValidationError{
			field:  "DesiredProfitPercent",
			reason: "value must be inside range [0, 100]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _GenerateRequest_Model_InLookup[m.GetModel()]; !ok {
		err := GenerateRequestValidationError{
			field:  "Model",
			reason: "value must be in list [B2C B2B]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetInitialBalance() < 0 {
		err := GenerateRequestValidationError{
			field:  "InitialBalance",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if val := m.GetScaleFactor(); val < 1 || val > 10 {
		err := GenerateRequestValidationError{
			field:  "ScaleFactor",
			reason: "value must be inside range [1, 10]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetCustomData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GenerateRequestValidationError{
					field:  "CustomData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GenerateRequestValidationError{
					field:  "CustomData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCustomData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GenerateRequestValidationError{
				field:  "CustomData",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GenerateRequestMultiError(errors)
	}

	return nil
}

// GenerateRequestMultiError is an error wrapping multiple validation errors
// returned by GenerateRequest.ValidateAll() if the designated constraints
// aren't met.
type GenerateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenerateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenerateRequestMultiError) AllErrors() []error { return m }

// GenerateRequestValidationError is the validation error returned by
// GenerateRequest.Validate if the designated constraints aren't met.
type GenerateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenerateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenerateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenerateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenerateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenerateRequestValidationError) ErrorName() string { return "GenerateRequestValidationError" }

// Error satisfies the builtin error interface
func (e GenerateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenerateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenerateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenerateRequestValidationError{}

var _GenerateRequest_Model_InLookup = map[string]struct{}{
	"B2C": {},
	"B2B": {},
}

// Validate checks the field values on CustomData with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CustomData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CustomData with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CustomDataMultiError, or
// nil if none found.
func (m *CustomData) ValidateAll() error {
	return m.validate(true)
}

func (m *CustomData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetManualTransactions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CustomDataValidationError{
						field:  fmt.Sprintf("ManualTransactions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CustomDataValidationError{
						field:  fmt.Sprintf("ManualTransactions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CustomDataValidationError{
					field:  fmt.Sprintf("ManualTransactions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetCompanyInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CustomDataValidationError{
					field:  "CompanyInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CustomDataValidationError{
					field:  "CompanyInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCompanyInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CustomDataValidationError{
				field:  "CompanyInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetCustomContractors() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CustomDataValidationError{
						field:  fmt.Sprintf("CustomContractors[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CustomDataValidationError{
						field:  fmt.Sprintf("CustomContractors[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CustomDataValidationError{
					field:  fmt.Sprintf("CustomContractors[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CustomDataMultiError(errors)
	}

	return nil
}

// CustomDataMultiError is an error wrapping multiple validation errors
// returned by CustomData.ValidateAll() if the designated constraints aren't met.
type CustomDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CustomDataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CustomDataMultiError) AllErrors() []error { return m }

// CustomDataValidationError is the validation error returned by
// CustomData.Validate if the designated constraints aren't met.
type CustomDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CustomDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CustomDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CustomDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CustomDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CustomDataValidationError) ErrorName() string { return "CustomDataValidationError" }

// Error satisfies the builtin error interface
func (e CustomDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCustomData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CustomDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CustomDataValidationError{}

// Validate checks the field values on ManualTransaction with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ManualTransaction) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ManualTransaction with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ManualTransactionMultiError, or nil if none found.
func (m *ManualTransaction) ValidateAll() error {
	return m.validate(true)
}

func (m *ManualTransaction) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetTransactionDate()) < 1 {
		err := ManualTransactionValidationError{
			field:  "TransactionDate",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetType()) < 1 {
		err := ManualTransactionValidationError{
			field:  "Type",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCategory()) < 1 {
		err := ManualTransactionValidationError{
			field:  "Category",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetMethod()) < 1 {
		err := ManualTransactionValidationError{
			field:  "Method",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ManualTransactionMultiError(errors)
	}

	return nil
}

// ManualTransactionMultiError is an error wrapping multiple validation errors
// returned by ManualTransaction.ValidateAll() if the designated constraints
// aren't met.
type ManualTransactionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ManualTransactionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ManualTransactionMultiError) AllErrors() []error { return m }

// ManualTransactionValidationError is the validation error returned by
// ManualTransaction.Validate if the designated constraints aren't met.
type ManualTransactionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ManualTransactionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ManualTransactionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ManualTransactionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ManualTransactionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ManualTransactionValidationError) ErrorName() string {
	return "ManualTransactionValidationError"
}

// Error satisfies the builtin error interface
func (e ManualTransactionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sManualTransaction.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ManualTransactionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ManualTransactionValidationError{}

// Validate checks the field values on CompanyInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CompanyInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CompanyInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CompanyInfoMultiError, or
// nil if none found.
func (m *CompanyInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *CompanyInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OwnerName

	// no validation rules for CompanyName

	if len(errors) > 0 {
		return CompanyInfoMultiError(errors)
	}

	return nil
}

// CompanyInfoMultiError is an error wrapping multiple validation errors
// returned by CompanyInfo.ValidateAll() if the designated constraints aren't met.
type CompanyInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CompanyInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CompanyInfoMultiError) AllErrors() []error { return m }

// CompanyInfoValidationError is the validation error returned by
// CompanyInfo.Validate if the designated constraints aren't met.
type CompanyInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CompanyInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CompanyInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CompanyInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CompanyInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CompanyInfoValidationError) ErrorName() string { return "CompanyInfoValidationError" }

// Error satisfies the builtin error interface
func (e CompanyInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCompanyInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CompanyInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CompanyInfoValidationError{}

// Validate checks the field values on CustomContractor with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CustomContractor) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CustomContractor with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CustomContractorMultiError, or nil if none found.
func (m *CustomContractor) ValidateAll() error {
	return m.validate(true)
}

func (m *CustomContractor) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TransactionType

	// no validation rules for Name

	if len(errors) > 0 {
		return CustomContractorMultiError(errors)
	}

	return nil
}

// CustomContractorMultiError is an error wrapping multiple validation errors
// returned by CustomContractor.ValidateAll() if the designated constraints
// aren't met.
type CustomContractorMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CustomContractorMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CustomContractorMultiError) AllErrors() []error { return m }

// CustomContractorValidationError is the validation error returned by
// CustomContractor.Validate if the designated constraints aren't met.
type CustomContractorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CustomContractorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CustomContractorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CustomContractorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CustomContractorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CustomContractorValidationError) ErrorName() string { return "CustomContractorValidationError" }

// Error satisfies the builtin error interface
func (e CustomContractorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCustomContractor.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CustomContractorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CustomContractorValidationError{}

// Validate checks the field values on GenerateResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GenerateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenerateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GenerateResponseMultiError, or nil if none found.
func (m *GenerateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GenerateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RequestId

	for idx, item := range m.GetTransactions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GenerateResponseValidationError{
						field:  fmt.Sprintf("Transactions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GenerateResponseValidationError{
						field:  fmt.Sprintf("Transactions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GenerateResponseValidationError{
					field:  fmt.Sprintf("Transactions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetFinancialSummary()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GenerateResponseValidationError{
					field:  "FinancialSummary",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GenerateResponseValidationError{
					field:  "FinancialSummary",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFinancialSummary()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GenerateResponseValidationError{
				field:  "FinancialSummary",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetDailyBalances() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GenerateResponseValidationError{
						field:  fmt.Sprintf("DailyBalances[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GenerateResponseValidationError{
						field:  fmt.Sprintf("DailyBalances[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GenerateResponseValidationError{
					field:  fmt.Sprintf("DailyBalances[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetForwardingInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GenerateResponseValidationError{
					field:  "ForwardingInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GenerateResponseValidationError{
					field:  "ForwardingInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetForwardingInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GenerateResponseValidationError{
				field:  "ForwardingInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetRevenueBreakdown()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GenerateResponseValidationError{
					field:  "RevenueBreakdown",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GenerateResponseValidationError{
					field:  "RevenueBreakdown",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRevenueBreakdown()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GenerateResponseValidationError{
				field:  "RevenueBreakdown",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetExpensesBreakdown()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GenerateResponseValidationError{
					field:  "ExpensesBreakdown",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GenerateResponseValidationError{
					field:  "ExpensesBreakdown",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpensesBreakdown()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GenerateResponseValidationError{
				field:  "ExpensesBreakdown",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetTransactionCounts()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GenerateResponseValidationError{
					field:  "TransactionCounts",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GenerateResponseValidationError{
					field:  "TransactionCounts",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTransactionCounts()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GenerateResponseValidationError{
				field:  "TransactionCounts",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GenerateResponseMultiError(errors)
	}

	return nil
}

// GenerateResponseMultiError is an error wrapping multiple validation errors
// returned by GenerateResponse.ValidateAll() if the designated constraints
// aren't met.
type GenerateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenerateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenerateResponseMultiError) AllErrors() []error { return m }

// GenerateResponseValidationError is the validation error returned by
// GenerateResponse.Validate if the designated constraints aren't met.
type GenerateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenerateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenerateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenerateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenerateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenerateResponseValidationError) ErrorName() string { return "GenerateResponseValidationError" }

// Error satisfies the builtin error interface
func (e GenerateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenerateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenerateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenerateResponseValidationError{}

// Validate checks the field values on FinancialSummary with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *FinancialSummary) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FinancialSummary with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FinancialSummaryMultiError, or nil if none found.
func (m *FinancialSummary) ValidateAll() error {
	return m.validate(true)
}

func (m *FinancialSummary) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for InitialBalance

	// no validation rules for FinalBalance

	// no validation rules for TotalRevenue

	// no validation rules for TotalExpenses

	// no validation rules for NetProfit

	if len(errors) > 0 {
		return FinancialSummaryMultiError(errors)
	}

	return nil
}

// FinancialSummaryMultiError is an error wrapping multiple validation errors
// returned by FinancialSummary.ValidateAll() if the designated constraints
// aren't met.
type FinancialSummaryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FinancialSummaryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FinancialSummaryMultiError) AllErrors() []error { return m }

// FinancialSummaryValidationError is the validation error returned by
// FinancialSummary.Validate if the designated constraints aren't met.
type FinancialSummaryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FinancialSummaryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FinancialSummaryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FinancialSummaryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FinancialSummaryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FinancialSummaryValidationError) ErrorName() string { return "FinancialSummaryValidationError" }

// Error satisfies the builtin error interface
func (e FinancialSummaryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFinancialSummary.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FinancialSummaryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FinancialSummaryValidationError{}

// Validate checks the field values on Transaction with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Transaction) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Transaction with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TransactionMultiError, or
// nil if none found.
func (m *Transaction) ValidateAll() error {
	return m.validate(true)
}

func (m *Transaction) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TransactionId

	// no validation rules for TransactionDate

	// no validation rules for PostingDate

	// no validation rules for Type

	// no validation rules for Category

	// no validation rules for Method

	// no validation rules for Amount

	// no validation rules for BalanceAfter

	// no validation rules for IsManual

	// no validation rules for SortOrder

	// no validation rules for CalculationDetails

	if len(errors) > 0 {
		return TransactionMultiError(errors)
	}

	return nil
}

// TransactionMultiError is an error wrapping multiple validation errors
// returned by Transaction.ValidateAll() if the designated constraints aren't met.
type TransactionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TransactionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TransactionMultiError) AllErrors() []error { return m }

// TransactionValidationError is the validation error returned by
// Transaction.Validate if the designated constraints aren't met.
type TransactionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TransactionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TransactionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TransactionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TransactionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TransactionValidationError) ErrorName() string { return "TransactionValidationError" }

// Error satisfies the builtin error interface
func (e TransactionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransaction.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TransactionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TransactionValidationError{}

// Validate checks the field values on DailyBalance with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DailyBalance) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DailyBalance with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DailyBalanceMultiError, or
// nil if none found.
func (m *DailyBalance) ValidateAll() error {
	return m.validate(true)
}

func (m *DailyBalance) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Date

	// no validation rules for Balance

	if len(errors) > 0 {
		return DailyBalanceMultiError(errors)
	}

	return nil
}

// DailyBalanceMultiError is an error wrapping multiple validation errors
// returned by DailyBalance.ValidateAll() if the designated constraints aren't met.
type DailyBalanceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DailyBalanceMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DailyBalanceMultiError) AllErrors() []error { return m }

// DailyBalanceValidationError is the validation error returned by
// DailyBalance.Validate if the designated constraints aren't met.
type DailyBalanceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DailyBalanceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DailyBalanceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DailyBalanceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DailyBalanceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DailyBalanceValidationError) ErrorName() string { return "DailyBalanceValidationError" }

// Error satisfies the builtin error interface
func (e DailyBalanceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDailyBalance.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DailyBalanceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DailyBalanceValidationError{}

// Validate checks the field values on ForwardingInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ForwardingInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ForwardingInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ForwardingInfoMultiError,
// or nil if none found.
func (m *ForwardingInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *ForwardingInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AssociatedCard

	// no validation rules for OwnerName

	// no validation rules for CompanyName

	for idx, item := range m.GetCustomContractors() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ForwardingInfoValidationError{
						field:  fmt.Sprintf("CustomContractors[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ForwardingInfoValidationError{
						field:  fmt.Sprintf("CustomContractors[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ForwardingInfoValidationError{
					field:  fmt.Sprintf("CustomContractors[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ForwardingInfoMultiError(errors)
	}

	return nil
}

// ForwardingInfoMultiError is an error wrapping multiple validation errors
// returned by ForwardingInfo.ValidateAll() if the designated constraints
// aren't met.
type ForwardingInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ForwardingInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ForwardingInfoMultiError) AllErrors() []error { return m }

// ForwardingInfoValidationError is the validation error returned by
// ForwardingInfo.Validate if the designated constraints aren't met.
type ForwardingInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ForwardingInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ForwardingInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ForwardingInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ForwardingInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ForwardingInfoValidationError) ErrorName() string { return "ForwardingInfoValidationError" }

// Error satisfies the builtin error interface
func (e ForwardingInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sForwardingInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ForwardingInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ForwardingInfoValidationError{}

// Validate checks the field values on TransactionCounts with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TransactionCounts) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TransactionCounts with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TransactionCountsMultiError, or nil if none found.
func (m *TransactionCounts) ValidateAll() error {
	return m.validate(true)
}

func (m *TransactionCounts) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TotalTransactions

	// no validation rules for TotalIncome

	// no validation rules for TotalExpenses

	if len(errors) > 0 {
		return TransactionCountsMultiError(errors)
	}

	return nil
}

// TransactionCountsMultiError is an error wrapping multiple validation errors
// returned by TransactionCounts.ValidateAll() if the designated constraints
// aren't met.
type TransactionCountsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TransactionCountsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TransactionCountsMultiError) AllErrors() []error { return m }

// TransactionCountsValidationError is the validation error returned by
// TransactionCounts.Validate if the designated constraints aren't met.
type TransactionCountsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TransactionCountsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TransactionCountsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TransactionCountsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TransactionCountsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TransactionCountsValidationError) ErrorName() string {
	return "TransactionCountsValidationError"
}

// Error satisfies the builtin error interface
func (e TransactionCountsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransactionCounts.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TransactionCountsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TransactionCountsValidationError{}
