// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: generate.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Month                int32                  `protobuf:"varint,1,opt,name=month,proto3" json:"month,omitempty"`
	Year                 int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Turnover             float64                `protobuf:"fixed64,3,opt,name=turnover,proto3" json:"turnover,omitempty"`
	DesiredProfitPercent float64                `protobuf:"fixed64,4,opt,name=desired_profit_percent,json=desiredProfitPercent,proto3" json:"desired_profit_percent,omitempty"`
	Model                string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	InitialBalance       float64                `protobuf:"fixed64,6,opt,name=initial_balance,json=initialBalance,proto3" json:"initial_balance,omitempty"`
	ScaleFactor          int32                  `protobuf:"varint,7,opt,name=scale_factor,json=scaleFactor,proto3" json:"scale_factor,omitempty"`
	CustomData           *CustomData            `protobuf:"bytes,8,opt,name=custom_data,json=customData,proto3" json:"custom_data,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_generate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *GenerateRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GenerateRequest) GetTurnover() float64 {
	if x != nil {
		return x.Turnover
	}
	return 0
}

func (x *GenerateRequest) GetDesiredProfitPercent() float64 {
	if x != nil {
		return x.DesiredProfitPercent
	}
	return 0
}

func (x *GenerateRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateRequest) GetInitialBalance() float64 {
	if x != nil {
		return x.InitialBalance
	}
	return 0
}

func (x *GenerateRequest) GetScaleFactor() int32 {
	if x != nil {
		return x.ScaleFactor
	}
	return 0
}

func (x *GenerateRequest) GetCustomData() *CustomData {
	if x != nil {
		return x.CustomData
	}
	return nil
}

type CustomData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ManualTransactions []*ManualTransaction   `protobuf:"bytes,1,rep,name=manual_transactions,json=manualTransactions,proto3" json:"manual_transactions,omitempty"`
	CompanyInfo        *CompanyInfo           `protobuf:"bytes,2,opt,name=company_info,json=companyInfo,proto3" json:"company_info,omitempty"`
	CustomCustomers    []string               `protobuf:"bytes,3,rep,name=custom_customers,json=customCustomers,proto3" json:"custom_customers,omitempty"`
	CustomContractors  []*CustomContractor    `protobuf:"bytes,4,rep,name=custom_contractors,json=customContractors,proto3" json:"custom_contractors,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CustomData) Reset() {
	*x = CustomData{}
	mi := &file_generate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomData) ProtoMessage() {}

func (x *CustomData) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomData.ProtoReflect.Descriptor instead.
func (*CustomData) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{1}
}

func (x *CustomData) GetManualTransactions() []*ManualTransaction {
	if x != nil {
		return x.ManualTransactions
	}
	return nil
}

func (x *CustomData) GetCompanyInfo() *CompanyInfo {
	if x != nil {
		return x.CompanyInfo
	}
	return nil
}

func (x *CustomData) GetCustomCustomers() []string {
	if x != nil {
		return x.CustomCustomers
	}
	return nil
}

func (x *CustomData) GetCustomContractors() []*CustomContractor {
	if x != nil {
		return x.CustomContractors
	}
	return nil
}

type ManualTransaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionDate string                 `protobuf:"bytes,1,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Category        string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Method          string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Amount          float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"` // Any amount is valid
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ManualTransaction) Reset() {
	*x = ManualTransaction{}
	mi := &file_generate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualTransaction) ProtoMessage() {}

func (x *ManualTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualTransaction.ProtoReflect.Descriptor instead.
func (*ManualTransaction) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{2}
}

func (x *ManualTransaction) GetTransactionDate() string {
	if x != nil {
		return x.TransactionDate
	}
	return ""
}

func (x *ManualTransaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ManualTransaction) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ManualTransaction) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ManualTransaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CompanyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerName     string                 `protobuf:"bytes,1,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	CompanyName   string                 `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanyInfo) Reset() {
	*x = CompanyInfo{}
	mi := &file_generate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyInfo) ProtoMessage() {}

func (x *CompanyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyInfo.ProtoReflect.Descriptor instead.
func (*CompanyInfo) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{3}
}

func (x *CompanyInfo) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *CompanyInfo) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

type CustomContractor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionType string                 `protobuf:"bytes,1,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CustomContractor) Reset() {
	*x = CustomContractor{}
	mi := &file_generate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomContractor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomContractor) ProtoMessage() {}

func (x *CustomContractor) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomContractor.ProtoReflect.Descriptor instead.
func (*CustomContractor) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{4}
}

func (x *CustomContractor) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *CustomContractor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GenerateResponse struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	RequestId         string                  `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Transactions      []*GeneratedTransaction `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	FinancialSummary  *FinancialSummary       `protobuf:"bytes,3,opt,name=financial_summary,json=financialSummary,proto3" json:"financial_summary,omitempty"`
	DailyBalances     []*DailyBalance         `protobuf:"bytes,4,rep,name=daily_balances,json=dailyBalances,proto3" json:"daily_balances,omitempty"`
	ForwardingInfo    *ForwardingInfo         `protobuf:"bytes,5,opt,name=forwarding_info,json=forwardingInfo,proto3" json:"forwarding_info,omitempty"`
	RevenueBreakdown  *RevenueBreakdown       `protobuf:"bytes,6,opt,name=revenue_breakdown,json=revenueBreakdown,proto3" json:"revenue_breakdown,omitempty"`
	ExpensesBreakdown *ExpensesBreakdown      `protobuf:"bytes,7,opt,name=expenses_breakdown,json=expensesBreakdown,proto3" json:"expenses_breakdown,omitempty"`
	TransactionCounts *TransactionCounts      `protobuf:"bytes,8,opt,name=transaction_counts,json=transactionCounts,proto3" json:"transaction_counts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_generate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GenerateResponse) GetTransactions() []*GeneratedTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GenerateResponse) GetFinancialSummary() *FinancialSummary {
	if x != nil {
		return x.FinancialSummary
	}
	return nil
}

func (x *GenerateResponse) GetDailyBalances() []*DailyBalance {
	if x != nil {
		return x.DailyBalances
	}
	return nil
}

func (x *GenerateResponse) GetForwardingInfo() *ForwardingInfo {
	if x != nil {
		return x.ForwardingInfo
	}
	return nil
}

func (x *GenerateResponse) GetRevenueBreakdown() *RevenueBreakdown {
	if x != nil {
		return x.RevenueBreakdown
	}
	return nil
}

func (x *GenerateResponse) GetExpensesBreakdown() *ExpensesBreakdown {
	if x != nil {
		return x.ExpensesBreakdown
	}
	return nil
}

func (x *GenerateResponse) GetTransactionCounts() *TransactionCounts {
	if x != nil {
		return x.TransactionCounts
	}
	return nil
}

type FinancialSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InitialBalance float64                `protobuf:"fixed64,1,opt,name=initial_balance,json=initialBalance,proto3" json:"initial_balance,omitempty"`
	FinalBalance   float64                `protobuf:"fixed64,2,opt,name=final_balance,json=finalBalance,proto3" json:"final_balance,omitempty"`
	TotalRevenue   float64                `protobuf:"fixed64,3,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	TotalExpenses  float64                `protobuf:"fixed64,4,opt,name=total_expenses,json=totalExpenses,proto3" json:"total_expenses,omitempty"`
	NetProfit      float64                `protobuf:"fixed64,5,opt,name=net_profit,json=netProfit,proto3" json:"net_profit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FinancialSummary) Reset() {
	*x = FinancialSummary{}
	mi := &file_generate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinancialSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinancialSummary) ProtoMessage() {}

func (x *FinancialSummary) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinancialSummary.ProtoReflect.Descriptor instead.
func (*FinancialSummary) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{6}
}

func (x *FinancialSummary) GetInitialBalance() float64 {
	if x != nil {
		return x.InitialBalance
	}
	return 0
}

func (x *FinancialSummary) GetFinalBalance() float64 {
	if x != nil {
		return x.FinalBalance
	}
	return 0
}

func (x *FinancialSummary) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *FinancialSummary) GetTotalExpenses() float64 {
	if x != nil {
		return x.TotalExpenses
	}
	return 0
}

func (x *FinancialSummary) GetNetProfit() float64 {
	if x != nil {
		return x.NetProfit
	}
	return 0
}

type Transaction struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TransactionId      string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	TransactionDate    string                 `protobuf:"bytes,2,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"`
	PostingDate        string                 `protobuf:"bytes,3,opt,name=posting_date,json=postingDate,proto3" json:"posting_date,omitempty"`
	Type               string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Category           string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Method             string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	Amount             float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	BalanceAfter       float64                `protobuf:"fixed64,8,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	IsManual           bool                   `protobuf:"varint,9,opt,name=is_manual,json=isManual,proto3" json:"is_manual,omitempty"`
	SortOrder          int32                  `protobuf:"varint,10,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	CalculationDetails map[string]string      `protobuf:"bytes,11,rep,name=calculation_details,json=calculationDetails,proto3" json:"calculation_details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_generate_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{7}
}

func (x *Transaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Transaction) GetTransactionDate() string {
	if x != nil {
		return x.TransactionDate
	}
	return ""
}

func (x *Transaction) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Transaction) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetBalanceAfter() float64 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *Transaction) GetIsManual() bool {
	if x != nil {
		return x.IsManual
	}
	return false
}

func (x *Transaction) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Transaction) GetCalculationDetails() map[string]string {
	if x != nil {
		return x.CalculationDetails
	}
	return nil
}

type DailyBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyBalance) Reset() {
	*x = DailyBalance{}
	mi := &file_generate_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyBalance) ProtoMessage() {}

func (x *DailyBalance) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyBalance.ProtoReflect.Descriptor instead.
func (*DailyBalance) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{8}
}

func (x *DailyBalance) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyBalance) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type ForwardingInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AssociatedCard    string                 `protobuf:"bytes,1,opt,name=associated_card,json=associatedCard,proto3" json:"associated_card,omitempty"`
	OwnerName         string                 `protobuf:"bytes,2,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	CompanyName       string                 `protobuf:"bytes,3,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	CustomCustomers   []string               `protobuf:"bytes,4,rep,name=custom_customers,json=customCustomers,proto3" json:"custom_customers,omitempty"`
	CustomContractors []*CustomContractor    `protobuf:"bytes,5,rep,name=custom_contractors,json=customContractors,proto3" json:"custom_contractors,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ForwardingInfo) Reset() {
	*x = ForwardingInfo{}
	mi := &file_generate_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardingInfo) ProtoMessage() {}

func (x *ForwardingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardingInfo.ProtoReflect.Descriptor instead.
func (*ForwardingInfo) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{9}
}

func (x *ForwardingInfo) GetAssociatedCard() string {
	if x != nil {
		return x.AssociatedCard
	}
	return ""
}

func (x *ForwardingInfo) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *ForwardingInfo) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *ForwardingInfo) GetCustomCustomers() []string {
	if x != nil {
		return x.CustomCustomers
	}
	return nil
}

func (x *ForwardingInfo) GetCustomContractors() []*CustomContractor {
	if x != nil {
		return x.CustomContractors
	}
	return nil
}

type TransactionCounts struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalTransactions int32                  `protobuf:"varint,1,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalIncome       int32                  `protobuf:"varint,2,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	TotalExpenses     int32                  `protobuf:"varint,3,opt,name=total_expenses,json=totalExpenses,proto3" json:"total_expenses,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransactionCounts) Reset() {
	*x = TransactionCounts{}
	mi := &file_generate_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionCounts) ProtoMessage() {}

func (x *TransactionCounts) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionCounts.ProtoReflect.Descriptor instead.
func (*TransactionCounts) Descriptor() ([]byte, []int) {
	return file_generate_proto_rawDescGZIP(), []int{10}
}

func (x *TransactionCounts) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *TransactionCounts) GetTotalIncome() int32 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

func (x *TransactionCounts) GetTotalExpenses() int32 {
	if x != nil {
		return x.TotalExpenses
	}
	return 0
}

var File_generate_proto protoreflect.FileDescriptor

const file_generate_proto_rawDesc = "" +
	"\n" +
	"\x0egenerate.proto\x12\bgenerate\x1a\fcommon.proto\x1a\x17validate/validate.proto\"\x93\x03\n" +
	"\x0fGenerateRequest\x12\x1f\n" +
	"\x05month\x18\x01 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\f(\x01R\x05month\x12\x1f\n" +
	"\x04year\x18\x02 \x01(\x05B\v\xfaB\b\x1a\x06\x18\xb4\x10(\xd0\x0fR\x04year\x12*\n" +
	"\bturnover\x18\x03 \x01(\x01B\x0e\xfaB\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\bturnover\x12M\n" +
	"\x16desired_profit_percent\x18\x04 \x01(\x01B\x17\xfaB\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00Y@)\x00\x00\x00\x00\x00\x00\x00\x00R\x14desiredProfitPercent\x12%\n" +
	"\x05model\x18\x05 \x01(\tB\x0f\xfaB\fr\n" +
	"R\x03B2CR\x03B2BR\x05model\x127\n" +
	"\x0finitial_balance\x18\x06 \x01(\x01B\x0e\xfaB\v\x12\t)\x00\x00\x00\x00\x00\x00\x00\x00R\x0einitialBalance\x12,\n" +
	"\fscale_factor\x18\a \x01(\x05B\t\xfaB\x06\x1a\x04\x18\n" +
	"(\x01R\vscaleFactor\x125\n" +
	"\vcustom_data\x18\b \x01(\v2\x14.generate.CustomDataR\n" +
	"customData\"\x8a\x02\n" +
	"\n" +
	"CustomData\x12L\n" +
	"\x13manual_transactions\x18\x01 \x03(\v2\x1b.generate.ManualTransactionR\x12manualTransactions\x128\n" +
	"\fcompany_info\x18\x02 \x01(\v2\x15.generate.CompanyInfoR\vcompanyInfo\x12)\n" +
	"\x10custom_customers\x18\x03 \x03(\tR\x0fcustomCustomers\x12I\n" +
	"\x12custom_contractors\x18\x04 \x03(\v2\x1a.generate.CustomContractorR\x11customContractors\"\xc9\x01\n" +
	"\x11ManualTransaction\x122\n" +
	"\x10transaction_date\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x0ftransactionDate\x12\x1b\n" +
	"\x04type\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04type\x12#\n" +
	"\bcategory\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bcategory\x12\x1f\n" +
	"\x06method\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06method\x12\x1d\n" +
	"\x06amount\x18\x05 \x01(\x01B\x05\xfaB\x02\x12\x00R\x06amount\"O\n" +
	"\vCompanyInfo\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x01 \x01(\tR\townerName\x12!\n" +
	"\fcompany_name\x18\x02 \x01(\tR\vcompanyName\"Q\n" +
	"\x10CustomContractor\x12)\n" +
	"\x10transaction_type\x18\x01 \x01(\tR\x0ftransactionType\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x9b\x04\n" +
	"\x10GenerateResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12@\n" +
	"\ftransactions\x18\x02 \x03(\v2\x1c.common.GeneratedTransactionR\ftransactions\x12G\n" +
	"\x11financial_summary\x18\x03 \x01(\v2\x1a.generate.FinancialSummaryR\x10financialSummary\x12=\n" +
	"\x0edaily_balances\x18\x04 \x03(\v2\x16.generate.DailyBalanceR\rdailyBalances\x12A\n" +
	"\x0fforwarding_info\x18\x05 \x01(\v2\x18.generate.ForwardingInfoR\x0eforwardingInfo\x12E\n" +
	"\x11revenue_breakdown\x18\x06 \x01(\v2\x18.common.RevenueBreakdownR\x10revenueBreakdown\x12H\n" +
	"\x12expenses_breakdown\x18\a \x01(\v2\x19.common.ExpensesBreakdownR\x11expensesBreakdown\x12J\n" +
	"\x12transaction_counts\x18\b \x01(\v2\x1b.generate.TransactionCountsR\x11transactionCounts\"\xcb\x01\n" +
	"\x10FinancialSummary\x12'\n" +
	"\x0finitial_balance\x18\x01 \x01(\x01R\x0einitialBalance\x12#\n" +
	"\rfinal_balance\x18\x02 \x01(\x01R\ffinalBalance\x12#\n" +
	"\rtotal_revenue\x18\x03 \x01(\x01R\ftotalRevenue\x12%\n" +
	"\x0etotal_expenses\x18\x04 \x01(\x01R\rtotalExpenses\x12\x1d\n" +
	"\n" +
	"net_profit\x18\x05 \x01(\x01R\tnetProfit\"\xea\x03\n" +
	"\vTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12)\n" +
	"\x10transaction_date\x18\x02 \x01(\tR\x0ftransactionDate\x12!\n" +
	"\fposting_date\x18\x03 \x01(\tR\vpostingDate\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\x12#\n" +
	"\rbalance_after\x18\b \x01(\x01R\fbalanceAfter\x12\x1b\n" +
	"\tis_manual\x18\t \x01(\bR\bisManual\x12\x1d\n" +
	"\n" +
	"sort_order\x18\n" +
	" \x01(\x05R\tsortOrder\x12^\n" +
	"\x13calculation_details\x18\v \x03(\v2-.generate.Transaction.CalculationDetailsEntryR\x12calculationDetails\x1aE\n" +
	"\x17CalculationDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\fDailyBalance\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\"\xf1\x01\n" +
	"\x0eForwardingInfo\x12'\n" +
	"\x0fassociated_card\x18\x01 \x01(\tR\x0eassociatedCard\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x02 \x01(\tR\townerName\x12!\n" +
	"\fcompany_name\x18\x03 \x01(\tR\vcompanyName\x12)\n" +
	"\x10custom_customers\x18\x04 \x03(\tR\x0fcustomCustomers\x12I\n" +
	"\x12custom_contractors\x18\x05 \x03(\v2\x1a.generate.CustomContractorR\x11customContractors\"\x8c\x01\n" +
	"\x11TransactionCounts\x12-\n" +
	"\x12total_transactions\x18\x01 \x01(\x05R\x11totalTransactions\x12!\n" +
	"\ftotal_income\x18\x02 \x01(\x05R\vtotalIncome\x12%\n" +
	"\x0etotal_expenses\x18\x03 \x01(\x05R\rtotalExpenses2T\n" +
	"\x0fGenerateService\x12A\n" +
	"\bGenerate\x12\x19.generate.GenerateRequest\x1a\x1a.generate.GenerateResponseB/Z-github.com/IbadT/business_bank_back/pkg/protob\x06proto3"

var (
	file_generate_proto_rawDescOnce sync.Once
	file_generate_proto_rawDescData []byte
)

func file_generate_proto_rawDescGZIP() []byte {
	file_generate_proto_rawDescOnce.Do(func() {
		file_generate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_generate_proto_rawDesc), len(file_generate_proto_rawDesc)))
	})
	return file_generate_proto_rawDescData
}

var file_generate_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_generate_proto_goTypes = []any{
	(*GenerateRequest)(nil),      // 0: generate.GenerateRequest
	(*CustomData)(nil),           // 1: generate.CustomData
	(*ManualTransaction)(nil),    // 2: generate.ManualTransaction
	(*CompanyInfo)(nil),          // 3: generate.CompanyInfo
	(*CustomContractor)(nil),     // 4: generate.CustomContractor
	(*GenerateResponse)(nil),     // 5: generate.GenerateResponse
	(*FinancialSummary)(nil),     // 6: generate.FinancialSummary
	(*Transaction)(nil),          // 7: generate.Transaction
	(*DailyBalance)(nil),         // 8: generate.DailyBalance
	(*ForwardingInfo)(nil),       // 9: generate.ForwardingInfo
	(*TransactionCounts)(nil),    // 10: generate.TransactionCounts
	nil,                          // 11: generate.Transaction.CalculationDetailsEntry
	(*GeneratedTransaction)(nil), // 12: common.GeneratedTransaction
	(*RevenueBreakdown)(nil),     // 13: common.RevenueBreakdown
	(*ExpensesBreakdown)(nil),    // 14: common.ExpensesBreakdown
}
var file_generate_proto_depIdxs = []int32{
	1,  // 0: generate.GenerateRequest.custom_data:type_name -> generate.CustomData
	2,  // 1: generate.CustomData.manual_transactions:type_name -> generate.ManualTransaction
	3,  // 2: generate.CustomData.company_info:type_name -> generate.CompanyInfo
	4,  // 3: generate.CustomData.custom_contractors:type_name -> generate.CustomContractor
	12, // 4: generate.GenerateResponse.transactions:type_name -> common.GeneratedTransaction
	6,  // 5: generate.GenerateResponse.financial_summary:type_name -> generate.FinancialSummary
	8,  // 6: generate.GenerateResponse.daily_balances:type_name -> generate.DailyBalance
	9,  // 7: generate.GenerateResponse.forwarding_info:type_name -> generate.ForwardingInfo
	13, // 8: generate.GenerateResponse.revenue_breakdown:type_name -> common.RevenueBreakdown
	14, // 9: generate.GenerateResponse.expenses_breakdown:type_name -> common.ExpensesBreakdown
	10, // 10: generate.GenerateResponse.transaction_counts:type_name -> generate.TransactionCounts
	11, // 11: generate.Transaction.calculation_details:type_name -> generate.Transaction.CalculationDetailsEntry
	4,  // 12: generate.ForwardingInfo.custom_contractors:type_name -> generate.CustomContractor
	0,  // 13: generate.GenerateService.Generate:input_type -> generate.GenerateRequest
	5,  // 14: generate.GenerateService.Generate:output_type -> generate.GenerateResponse
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_generate_proto_init() }
func file_generate_proto_init() {
	if File_generate_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_generate_proto_rawDesc), len(file_generate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_generate_proto_goTypes,
		DependencyIndexes: file_generate_proto_depIdxs,
		MessageInfos:      file_generate_proto_msgTypes,
	}.Build()
	File_generate_proto = out.File
	file_generate_proto_goTypes = nil
	file_generate_proto_depIdxs = nil
}
