// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: holidays.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _holidays_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Holiday with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Holiday) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Holiday with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in HolidayMultiError, or nil if none found.
func (m *Holiday) ValidateAll() error {
	return m.validate(true)
}

func (m *Holiday) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() != "" {

		if err := m._validateUuid(m.GetId()); err != nil {
			err = HolidayValidationError{
				field:  "Id",
				reason: "value must be a valid UUID",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if utf8.RuneCountInString(m.GetHolidayDate()) < 1 {
		err := HolidayValidationError{
			field:  "HolidayDate",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_Holiday_HolidayDate_Pattern.MatchString(m.GetHolidayDate()) {
		err := HolidayValidationError{
			field:  "HolidayDate",
			reason: "value does not match regex pattern \"^\\\\d{4}-\\\\d{2}-\\\\d{2}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := HolidayValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _Holiday_Country_InLookup[m.GetCountry()]; !ok {
		err := HolidayValidationError{
			field:  "Country",
			reason: "value must be in list [RU US]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return HolidayMultiError(errors)
	}

	return nil
}

func (m *Holiday) _validateUuid(uuid string) error {
	if matched := _holidays_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// HolidayMultiError is an error wrapping multiple validation errors returned
// by Holiday.ValidateAll() if the designated constraints aren't met.
type HolidayMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HolidayMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HolidayMultiError) AllErrors() []error { return m }

// HolidayValidationError is the validation error returned by Holiday.Validate
// if the designated constraints aren't met.
type HolidayValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HolidayValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HolidayValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HolidayValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HolidayValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HolidayValidationError) ErrorName() string { return "HolidayValidationError" }

// Error satisfies the builtin error interface
func (e HolidayValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHoliday.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HolidayValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HolidayValidationError{}

var _Holiday_HolidayDate_Pattern = regexp.MustCompile("^\\d{4}-\\d{2}-\\d{2}$")

var _Holiday_Country_InLookup = map[string]struct{}{
	"RU": {},
	"US": {},
}

// Validate checks the field values on AddHolidayRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AddHolidayRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddHolidayRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddHolidayRequestMultiError, or nil if none found.
func (m *AddHolidayRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AddHolidayRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetHoliday() == nil {
		err := AddHolidayRequestValidationError{
			field:  "Holiday",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetHoliday()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AddHolidayRequestValidationError{
					field:  "Holiday",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AddHolidayRequestValidationError{
					field:  "Holiday",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetHoliday()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AddHolidayRequestValidationError{
				field:  "Holiday",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AddHolidayRequestMultiError(errors)
	}

	return nil
}

// AddHolidayRequestMultiError is an error wrapping multiple validation errors
// returned by AddHolidayRequest.ValidateAll() if the designated constraints
// aren't met.
type AddHolidayRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddHolidayRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddHolidayRequestMultiError) AllErrors() []error { return m }

// AddHolidayRequestValidationError is the validation error returned by
// AddHolidayRequest.Validate if the designated constraints aren't met.
type AddHolidayRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddHolidayRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddHolidayRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddHolidayRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddHolidayRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddHolidayRequestValidationError) ErrorName() string {
	return "AddHolidayRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AddHolidayRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddHolidayRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddHolidayRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddHolidayRequestValidationError{}

// Validate checks the field values on AddHolidayResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AddHolidayResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AddHolidayResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AddHolidayResponseMultiError, or nil if none found.
func (m *AddHolidayResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AddHolidayResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	// no validation rules for Code

	if len(errors) > 0 {
		return AddHolidayResponseMultiError(errors)
	}

	return nil
}

// AddHolidayResponseMultiError is an error wrapping multiple validation errors
// returned by AddHolidayResponse.ValidateAll() if the designated constraints
// aren't met.
type AddHolidayResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AddHolidayResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AddHolidayResponseMultiError) AllErrors() []error { return m }

// AddHolidayResponseValidationError is the validation error returned by
// AddHolidayResponse.Validate if the designated constraints aren't met.
type AddHolidayResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AddHolidayResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AddHolidayResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AddHolidayResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AddHolidayResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AddHolidayResponseValidationError) ErrorName() string {
	return "AddHolidayResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AddHolidayResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAddHolidayResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AddHolidayResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AddHolidayResponseValidationError{}

// Validate checks the field values on GetHolidaysRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetHolidaysRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetHolidaysRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetHolidaysRequestMultiError, or nil if none found.
func (m *GetHolidaysRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetHolidaysRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetYear()) < 1 {
		err := GetHolidaysRequestValidationError{
			field:  "Year",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_GetHolidaysRequest_Year_Pattern.MatchString(m.GetYear()) {
		err := GetHolidaysRequestValidationError{
			field:  "Year",
			reason: "value does not match regex pattern \"^\\\\d{4}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetHolidaysRequestMultiError(errors)
	}

	return nil
}

// GetHolidaysRequestMultiError is an error wrapping multiple validation errors
// returned by GetHolidaysRequest.ValidateAll() if the designated constraints
// aren't met.
type GetHolidaysRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetHolidaysRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetHolidaysRequestMultiError) AllErrors() []error { return m }

// GetHolidaysRequestValidationError is the validation error returned by
// GetHolidaysRequest.Validate if the designated constraints aren't met.
type GetHolidaysRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetHolidaysRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetHolidaysRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetHolidaysRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetHolidaysRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetHolidaysRequestValidationError) ErrorName() string {
	return "GetHolidaysRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetHolidaysRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetHolidaysRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetHolidaysRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetHolidaysRequestValidationError{}

var _GetHolidaysRequest_Year_Pattern = regexp.MustCompile("^\\d{4}$")

// Validate checks the field values on GetHolidaysResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetHolidaysResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetHolidaysResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetHolidaysResponseMultiError, or nil if none found.
func (m *GetHolidaysResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetHolidaysResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetHolidays() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetHolidaysResponseValidationError{
						field:  fmt.Sprintf("Holidays[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetHolidaysResponseValidationError{
						field:  fmt.Sprintf("Holidays[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetHolidaysResponseValidationError{
					field:  fmt.Sprintf("Holidays[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Year

	if len(errors) > 0 {
		return GetHolidaysResponseMultiError(errors)
	}

	return nil
}

// GetHolidaysResponseMultiError is an error wrapping multiple validation
// errors returned by GetHolidaysResponse.ValidateAll() if the designated
// constraints aren't met.
type GetHolidaysResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetHolidaysResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetHolidaysResponseMultiError) AllErrors() []error { return m }

// GetHolidaysResponseValidationError is the validation error returned by
// GetHolidaysResponse.Validate if the designated constraints aren't met.
type GetHolidaysResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetHolidaysResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetHolidaysResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetHolidaysResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetHolidaysResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetHolidaysResponseValidationError) ErrorName() string {
	return "GetHolidaysResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetHolidaysResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetHolidaysResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetHolidaysResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetHolidaysResponseValidationError{}

// Validate checks the field values on CheckIsHolidayRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckIsHolidayRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckIsHolidayRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckIsHolidayRequestMultiError, or nil if none found.
func (m *CheckIsHolidayRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckIsHolidayRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetDate()) < 1 {
		err := CheckIsHolidayRequestValidationError{
			field:  "Date",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_CheckIsHolidayRequest_Date_Pattern.MatchString(m.GetDate()) {
		err := CheckIsHolidayRequestValidationError{
			field:  "Date",
			reason: "value does not match regex pattern \"^\\\\d{4}-\\\\d{2}-\\\\d{2}$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CheckIsHolidayRequestMultiError(errors)
	}

	return nil
}

// CheckIsHolidayRequestMultiError is an error wrapping multiple validation
// errors returned by CheckIsHolidayRequest.ValidateAll() if the designated
// constraints aren't met.
type CheckIsHolidayRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckIsHolidayRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckIsHolidayRequestMultiError) AllErrors() []error { return m }

// CheckIsHolidayRequestValidationError is the validation error returned by
// CheckIsHolidayRequest.Validate if the designated constraints aren't met.
type CheckIsHolidayRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckIsHolidayRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckIsHolidayRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckIsHolidayRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckIsHolidayRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckIsHolidayRequestValidationError) ErrorName() string {
	return "CheckIsHolidayRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CheckIsHolidayRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckIsHolidayRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckIsHolidayRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckIsHolidayRequestValidationError{}

var _CheckIsHolidayRequest_Date_Pattern = regexp.MustCompile("^\\d{4}-\\d{2}-\\d{2}$")

// Validate checks the field values on CheckIsHolidayResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckIsHolidayResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckIsHolidayResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckIsHolidayResponseMultiError, or nil if none found.
func (m *CheckIsHolidayResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckIsHolidayResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsHoliday

	// no validation rules for Date

	if len(errors) > 0 {
		return CheckIsHolidayResponseMultiError(errors)
	}

	return nil
}

// CheckIsHolidayResponseMultiError is an error wrapping multiple validation
// errors returned by CheckIsHolidayResponse.ValidateAll() if the designated
// constraints aren't met.
type CheckIsHolidayResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckIsHolidayResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckIsHolidayResponseMultiError) AllErrors() []error { return m }

// CheckIsHolidayResponseValidationError is the validation error returned by
// CheckIsHolidayResponse.Validate if the designated constraints aren't met.
type CheckIsHolidayResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckIsHolidayResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckIsHolidayResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckIsHolidayResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckIsHolidayResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckIsHolidayResponseValidationError) ErrorName() string {
	return "CheckIsHolidayResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CheckIsHolidayResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckIsHolidayResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckIsHolidayResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckIsHolidayResponseValidationError{}

// Validate checks the field values on UpdateHolidayRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateHolidayRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateHolidayRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateHolidayRequestMultiError, or nil if none found.
func (m *UpdateHolidayRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateHolidayRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetHoliday() == nil {
		err := UpdateHolidayRequestValidationError{
			field:  "Holiday",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetHoliday()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateHolidayRequestValidationError{
					field:  "Holiday",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateHolidayRequestValidationError{
					field:  "Holiday",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetHoliday()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateHolidayRequestValidationError{
				field:  "Holiday",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateHolidayRequestMultiError(errors)
	}

	return nil
}

// UpdateHolidayRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateHolidayRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateHolidayRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateHolidayRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateHolidayRequestMultiError) AllErrors() []error { return m }

// UpdateHolidayRequestValidationError is the validation error returned by
// UpdateHolidayRequest.Validate if the designated constraints aren't met.
type UpdateHolidayRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateHolidayRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateHolidayRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateHolidayRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateHolidayRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateHolidayRequestValidationError) ErrorName() string {
	return "UpdateHolidayRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateHolidayRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateHolidayRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateHolidayRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateHolidayRequestValidationError{}

// Validate checks the field values on UpdateHolidayResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateHolidayResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateHolidayResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateHolidayResponseMultiError, or nil if none found.
func (m *UpdateHolidayResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateHolidayResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	// no validation rules for Code

	if len(errors) > 0 {
		return UpdateHolidayResponseMultiError(errors)
	}

	return nil
}

// UpdateHolidayResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateHolidayResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateHolidayResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateHolidayResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateHolidayResponseMultiError) AllErrors() []error { return m }

// UpdateHolidayResponseValidationError is the validation error returned by
// UpdateHolidayResponse.Validate if the designated constraints aren't met.
type UpdateHolidayResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateHolidayResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateHolidayResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateHolidayResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateHolidayResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateHolidayResponseValidationError) ErrorName() string {
	return "UpdateHolidayResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateHolidayResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateHolidayResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateHolidayResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateHolidayResponseValidationError{}

// Validate checks the field values on DeleteHolidayRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteHolidayRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteHolidayRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteHolidayRequestMultiError, or nil if none found.
func (m *DeleteHolidayRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteHolidayRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := DeleteHolidayRequestValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetId()); err != nil {
		err = DeleteHolidayRequestValidationError{
			field:  "Id",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteHolidayRequestMultiError(errors)
	}

	return nil
}

func (m *DeleteHolidayRequest) _validateUuid(uuid string) error {
	if matched := _holidays_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// DeleteHolidayRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteHolidayRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteHolidayRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteHolidayRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteHolidayRequestMultiError) AllErrors() []error { return m }

// DeleteHolidayRequestValidationError is the validation error returned by
// DeleteHolidayRequest.Validate if the designated constraints aren't met.
type DeleteHolidayRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteHolidayRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteHolidayRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteHolidayRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteHolidayRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteHolidayRequestValidationError) ErrorName() string {
	return "DeleteHolidayRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteHolidayRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteHolidayRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteHolidayRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteHolidayRequestValidationError{}

// Validate checks the field values on DeleteHolidayResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteHolidayResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteHolidayResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteHolidayResponseMultiError, or nil if none found.
func (m *DeleteHolidayResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteHolidayResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	// no validation rules for Code

	if len(errors) > 0 {
		return DeleteHolidayResponseMultiError(errors)
	}

	return nil
}

// DeleteHolidayResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteHolidayResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteHolidayResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteHolidayResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteHolidayResponseMultiError) AllErrors() []error { return m }

// DeleteHolidayResponseValidationError is the validation error returned by
// DeleteHolidayResponse.Validate if the designated constraints aren't met.
type DeleteHolidayResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteHolidayResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteHolidayResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteHolidayResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteHolidayResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteHolidayResponseValidationError) ErrorName() string {
	return "DeleteHolidayResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteHolidayResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteHolidayResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteHolidayResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteHolidayResponseValidationError{}
