// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: transaction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TransactionDate string                 `protobuf:"bytes,2,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"`
	PostingDate     string                 `protobuf:"bytes,3,opt,name=posting_date,json=postingDate,proto3" json:"posting_date,omitempty"`
	Type            string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Category        string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Method          string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	Amount          float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateTransactionRequest) GetTransactionDate() string {
	if x != nil {
		return x.TransactionDate
	}
	return ""
}

func (x *CreateTransactionRequest) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

func (x *CreateTransactionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateTransactionRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateTransactionRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateTransactionResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type CreateBatchTransactionsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TransactionDate string                 `protobuf:"bytes,2,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"`
	PostingDate     string                 `protobuf:"bytes,3,opt,name=posting_date,json=postingDate,proto3" json:"posting_date,omitempty"`
	Type            string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Category        string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Method          string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	Amount          float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateBatchTransactionsRequest) Reset() {
	*x = CreateBatchTransactionsRequest{}
	mi := &file_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBatchTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBatchTransactionsRequest) ProtoMessage() {}

func (x *CreateBatchTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBatchTransactionsRequest.ProtoReflect.Descriptor instead.
func (*CreateBatchTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBatchTransactionsRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateBatchTransactionsRequest) GetTransactionDate() string {
	if x != nil {
		return x.TransactionDate
	}
	return ""
}

func (x *CreateBatchTransactionsRequest) GetPostingDate() string {
	if x != nil {
		return x.PostingDate
	}
	return ""
}

func (x *CreateBatchTransactionsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateBatchTransactionsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateBatchTransactionsRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CreateBatchTransactionsRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateBatchTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBatchTransactionsResponse) Reset() {
	*x = CreateBatchTransactionsResponse{}
	mi := &file_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBatchTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBatchTransactionsResponse) ProtoMessage() {}

func (x *CreateBatchTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBatchTransactionsResponse.ProtoReflect.Descriptor instead.
func (*CreateBatchTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBatchTransactionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateBatchTransactionsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type GetTransactionsCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsCountRequest) Reset() {
	*x = GetTransactionsCountRequest{}
	mi := &file_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsCountRequest) ProtoMessage() {}

func (x *GetTransactionsCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsCountRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsCountRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionsCountRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetTransactionsCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsCountResponse) Reset() {
	*x = GetTransactionsCountResponse{}
	mi := &file_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsCountResponse) ProtoMessage() {}

func (x *GetTransactionsCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsCountResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsCountResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *GetTransactionsCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetTransactionsCountResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type GetTransactionsByTypeAndRequestIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByTypeAndRequestIDRequest) Reset() {
	*x = GetTransactionsByTypeAndRequestIDRequest{}
	mi := &file_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByTypeAndRequestIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByTypeAndRequestIDRequest) ProtoMessage() {}

func (x *GetTransactionsByTypeAndRequestIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByTypeAndRequestIDRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsByTypeAndRequestIDRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransactionsByTypeAndRequestIDRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetTransactionsByTypeAndRequestIDRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetTransactionsByTypeAndRequestIDResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Transactions  []*GeneratedTransaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Code          int32                   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByTypeAndRequestIDResponse) Reset() {
	*x = GetTransactionsByTypeAndRequestIDResponse{}
	mi := &file_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByTypeAndRequestIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByTypeAndRequestIDResponse) ProtoMessage() {}

func (x *GetTransactionsByTypeAndRequestIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByTypeAndRequestIDResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsByTypeAndRequestIDResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransactionsByTypeAndRequestIDResponse) GetTransactions() []*GeneratedTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetTransactionsByTypeAndRequestIDResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type GetTransactionsByMethodAndRequestIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByMethodAndRequestIDRequest) Reset() {
	*x = GetTransactionsByMethodAndRequestIDRequest{}
	mi := &file_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByMethodAndRequestIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByMethodAndRequestIDRequest) ProtoMessage() {}

func (x *GetTransactionsByMethodAndRequestIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByMethodAndRequestIDRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsByMethodAndRequestIDRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *GetTransactionsByMethodAndRequestIDRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetTransactionsByMethodAndRequestIDRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type GetTransactionsByMethodAndRequestIDResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Transactions  []*GeneratedTransaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Code          int32                   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByMethodAndRequestIDResponse) Reset() {
	*x = GetTransactionsByMethodAndRequestIDResponse{}
	mi := &file_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByMethodAndRequestIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByMethodAndRequestIDResponse) ProtoMessage() {}

func (x *GetTransactionsByMethodAndRequestIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByMethodAndRequestIDResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsByMethodAndRequestIDResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *GetTransactionsByMethodAndRequestIDResponse) GetTransactions() []*GeneratedTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetTransactionsByMethodAndRequestIDResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type GetTransactionsByRequestIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByRequestIDRequest) Reset() {
	*x = GetTransactionsByRequestIDRequest{}
	mi := &file_transaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByRequestIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByRequestIDRequest) ProtoMessage() {}

func (x *GetTransactionsByRequestIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByRequestIDRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsByRequestIDRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{10}
}

func (x *GetTransactionsByRequestIDRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetTransactionsByRequestIDResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Transactions  []*GeneratedTransaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Code          int32                   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByRequestIDResponse) Reset() {
	*x = GetTransactionsByRequestIDResponse{}
	mi := &file_transaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByRequestIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByRequestIDResponse) ProtoMessage() {}

func (x *GetTransactionsByRequestIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByRequestIDResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsByRequestIDResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{11}
}

func (x *GetTransactionsByRequestIDResponse) GetTransactions() []*GeneratedTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetTransactionsByRequestIDResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\x12\vtransaction\x1a\fcommon.proto\"\xe7\x01\n" +
	"\x18CreateTransactionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12)\n" +
	"\x10transaction_date\x18\x02 \x01(\tR\x0ftransactionDate\x12!\n" +
	"\fposting_date\x18\x03 \x01(\tR\vpostingDate\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\"I\n" +
	"\x19CreateTransactionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"\xed\x01\n" +
	"\x1eCreateBatchTransactionsRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12)\n" +
	"\x10transaction_date\x18\x02 \x01(\tR\x0ftransactionDate\x12!\n" +
	"\fposting_date\x18\x03 \x01(\tR\vpostingDate\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\"O\n" +
	"\x1fCreateBatchTransactionsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"<\n" +
	"\x1bGetTransactionsCountRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"H\n" +
	"\x1cGetTransactionsCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"]\n" +
	"(GetTransactionsByTypeAndRequestIDRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x81\x01\n" +
	")GetTransactionsByTypeAndRequestIDResponse\x12@\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1c.common.GeneratedTransactionR\ftransactions\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"c\n" +
	"*GetTransactionsByMethodAndRequestIDRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\"\x83\x01\n" +
	"+GetTransactionsByMethodAndRequestIDResponse\x12@\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1c.common.GeneratedTransactionR\ftransactions\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"B\n" +
	"!GetTransactionsByRequestIDRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"z\n" +
	"\"GetTransactionsByRequestIDResponse\x12@\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1c.common.GeneratedTransactionR\ftransactions\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code2\x8a\x06\n" +
	"\x12TransactionService\x12b\n" +
	"\x11CreateTransaction\x12%.transaction.CreateTransactionRequest\x1a&.transaction.CreateTransactionResponse\x12t\n" +
	"\x17CreateBatchTransactions\x12+.transaction.CreateBatchTransactionsRequest\x1a,.transaction.CreateBatchTransactionsResponse\x12k\n" +
	"\x14GetTransactionsCount\x12(.transaction.GetTransactionsCountRequest\x1a).transaction.GetTransactionsCountResponse\x12\x92\x01\n" +
	"!GetTransactionsByTypeAndRequestID\x125.transaction.GetTransactionsByTypeAndRequestIDRequest\x1a6.transaction.GetTransactionsByTypeAndRequestIDResponse\x12\x98\x01\n" +
	"#GetTransactionsByMethodAndRequestID\x127.transaction.GetTransactionsByMethodAndRequestIDRequest\x1a8.transaction.GetTransactionsByMethodAndRequestIDResponse\x12}\n" +
	"\x1aGetTransactionsByRequestID\x12..transaction.GetTransactionsByRequestIDRequest\x1a/.transaction.GetTransactionsByRequestIDResponseB/Z-github.com/IbadT/business_bank_back/pkg/protob\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_transaction_proto_goTypes = []any{
	(*CreateTransactionRequest)(nil),                    // 0: transaction.CreateTransactionRequest
	(*CreateTransactionResponse)(nil),                   // 1: transaction.CreateTransactionResponse
	(*CreateBatchTransactionsRequest)(nil),              // 2: transaction.CreateBatchTransactionsRequest
	(*CreateBatchTransactionsResponse)(nil),             // 3: transaction.CreateBatchTransactionsResponse
	(*GetTransactionsCountRequest)(nil),                 // 4: transaction.GetTransactionsCountRequest
	(*GetTransactionsCountResponse)(nil),                // 5: transaction.GetTransactionsCountResponse
	(*GetTransactionsByTypeAndRequestIDRequest)(nil),    // 6: transaction.GetTransactionsByTypeAndRequestIDRequest
	(*GetTransactionsByTypeAndRequestIDResponse)(nil),   // 7: transaction.GetTransactionsByTypeAndRequestIDResponse
	(*GetTransactionsByMethodAndRequestIDRequest)(nil),  // 8: transaction.GetTransactionsByMethodAndRequestIDRequest
	(*GetTransactionsByMethodAndRequestIDResponse)(nil), // 9: transaction.GetTransactionsByMethodAndRequestIDResponse
	(*GetTransactionsByRequestIDRequest)(nil),           // 10: transaction.GetTransactionsByRequestIDRequest
	(*GetTransactionsByRequestIDResponse)(nil),          // 11: transaction.GetTransactionsByRequestIDResponse
	(*GeneratedTransaction)(nil),                        // 12: common.GeneratedTransaction
}
var file_transaction_proto_depIdxs = []int32{
	12, // 0: transaction.GetTransactionsByTypeAndRequestIDResponse.transactions:type_name -> common.GeneratedTransaction
	12, // 1: transaction.GetTransactionsByMethodAndRequestIDResponse.transactions:type_name -> common.GeneratedTransaction
	12, // 2: transaction.GetTransactionsByRequestIDResponse.transactions:type_name -> common.GeneratedTransaction
	0,  // 3: transaction.TransactionService.CreateTransaction:input_type -> transaction.CreateTransactionRequest
	2,  // 4: transaction.TransactionService.CreateBatchTransactions:input_type -> transaction.CreateBatchTransactionsRequest
	4,  // 5: transaction.TransactionService.GetTransactionsCount:input_type -> transaction.GetTransactionsCountRequest
	6,  // 6: transaction.TransactionService.GetTransactionsByTypeAndRequestID:input_type -> transaction.GetTransactionsByTypeAndRequestIDRequest
	8,  // 7: transaction.TransactionService.GetTransactionsByMethodAndRequestID:input_type -> transaction.GetTransactionsByMethodAndRequestIDRequest
	10, // 8: transaction.TransactionService.GetTransactionsByRequestID:input_type -> transaction.GetTransactionsByRequestIDRequest
	1,  // 9: transaction.TransactionService.CreateTransaction:output_type -> transaction.CreateTransactionResponse
	3,  // 10: transaction.TransactionService.CreateBatchTransactions:output_type -> transaction.CreateBatchTransactionsResponse
	5,  // 11: transaction.TransactionService.GetTransactionsCount:output_type -> transaction.GetTransactionsCountResponse
	7,  // 12: transaction.TransactionService.GetTransactionsByTypeAndRequestID:output_type -> transaction.GetTransactionsByTypeAndRequestIDResponse
	9,  // 13: transaction.TransactionService.GetTransactionsByMethodAndRequestID:output_type -> transaction.GetTransactionsByMethodAndRequestIDResponse
	11, // 14: transaction.TransactionService.GetTransactionsByRequestID:output_type -> transaction.GetTransactionsByRequestIDResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
