// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: transaction.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _transaction_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on CreateTransactionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateTransactionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTransactionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTransactionRequestMultiError, or nil if none found.
func (m *CreateTransactionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTransactionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetRequestId()) < 1 {
		err := CreateTransactionRequestValidationError{
			field:  "RequestId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetRequestId()); err != nil {
		err = CreateTransactionRequestValidationError{
			field:  "RequestId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetTransactionDate()) < 1 {
		err := CreateTransactionRequestValidationError{
			field:  "TransactionDate",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPostingDate() != "" {

		if !_CreateTransactionRequest_PostingDate_Pattern.MatchString(m.GetPostingDate()) {
			err := CreateTransactionRequestValidationError{
				field:  "PostingDate",
				reason: "value does not match regex pattern \"^\\\\d{4}-\\\\d{2}-\\\\d{2}$\"",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if utf8.RuneCountInString(m.GetType()) < 1 {
		err := CreateTransactionRequestValidationError{
			field:  "Type",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCategory()) < 1 {
		err := CreateTransactionRequestValidationError{
			field:  "Category",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetMethod()) < 1 {
		err := CreateTransactionRequestValidationError{
			field:  "Method",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateTransactionRequestMultiError(errors)
	}

	return nil
}

func (m *CreateTransactionRequest) _validateUuid(uuid string) error {
	if matched := _transaction_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// CreateTransactionRequestMultiError is an error wrapping multiple validation
// errors returned by CreateTransactionRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateTransactionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTransactionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTransactionRequestMultiError) AllErrors() []error { return m }

// CreateTransactionRequestValidationError is the validation error returned by
// CreateTransactionRequest.Validate if the designated constraints aren't met.
type CreateTransactionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTransactionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTransactionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTransactionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTransactionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTransactionRequestValidationError) ErrorName() string {
	return "CreateTransactionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTransactionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTransactionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTransactionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTransactionRequestValidationError{}

var _CreateTransactionRequest_PostingDate_Pattern = regexp.MustCompile("^\\d{4}-\\d{2}-\\d{2}$")

// Validate checks the field values on CreateTransactionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateTransactionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTransactionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTransactionResponseMultiError, or nil if none found.
func (m *CreateTransactionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTransactionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	// no validation rules for Code

	if len(errors) > 0 {
		return CreateTransactionResponseMultiError(errors)
	}

	return nil
}

// CreateTransactionResponseMultiError is an error wrapping multiple validation
// errors returned by CreateTransactionResponse.ValidateAll() if the
// designated constraints aren't met.
type CreateTransactionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTransactionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTransactionResponseMultiError) AllErrors() []error { return m }

// CreateTransactionResponseValidationError is the validation error returned by
// CreateTransactionResponse.Validate if the designated constraints aren't met.
type CreateTransactionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTransactionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTransactionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTransactionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTransactionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTransactionResponseValidationError) ErrorName() string {
	return "CreateTransactionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTransactionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTransactionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTransactionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTransactionResponseValidationError{}

// Validate checks the field values on CreateBatchTransactionsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateBatchTransactionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBatchTransactionsRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CreateBatchTransactionsRequestMultiError, or nil if none found.
func (m *CreateBatchTransactionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBatchTransactionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetRequestId()) < 1 {
		err := CreateBatchTransactionsRequestValidationError{
			field:  "RequestId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetRequestId()); err != nil {
		err = CreateBatchTransactionsRequestValidationError{
			field:  "RequestId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetTransactionDate()) < 1 {
		err := CreateBatchTransactionsRequestValidationError{
			field:  "TransactionDate",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetPostingDate() != "" {

		if !_CreateBatchTransactionsRequest_PostingDate_Pattern.MatchString(m.GetPostingDate()) {
			err := CreateBatchTransactionsRequestValidationError{
				field:  "PostingDate",
				reason: "value does not match regex pattern \"^\\\\d{4}-\\\\d{2}-\\\\d{2}$\"",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if utf8.RuneCountInString(m.GetType()) < 1 {
		err := CreateBatchTransactionsRequestValidationError{
			field:  "Type",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCategory()) < 1 {
		err := CreateBatchTransactionsRequestValidationError{
			field:  "Category",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetMethod()) < 1 {
		err := CreateBatchTransactionsRequestValidationError{
			field:  "Method",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateBatchTransactionsRequestMultiError(errors)
	}

	return nil
}

func (m *CreateBatchTransactionsRequest) _validateUuid(uuid string) error {
	if matched := _transaction_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// CreateBatchTransactionsRequestMultiError is an error wrapping multiple
// validation errors returned by CreateBatchTransactionsRequest.ValidateAll()
// if the designated constraints aren't met.
type CreateBatchTransactionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBatchTransactionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBatchTransactionsRequestMultiError) AllErrors() []error { return m }

// CreateBatchTransactionsRequestValidationError is the validation error
// returned by CreateBatchTransactionsRequest.Validate if the designated
// constraints aren't met.
type CreateBatchTransactionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBatchTransactionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBatchTransactionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBatchTransactionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBatchTransactionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBatchTransactionsRequestValidationError) ErrorName() string {
	return "CreateBatchTransactionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateBatchTransactionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBatchTransactionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBatchTransactionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBatchTransactionsRequestValidationError{}

var _CreateBatchTransactionsRequest_PostingDate_Pattern = regexp.MustCompile("^\\d{4}-\\d{2}-\\d{2}$")

// Validate checks the field values on CreateBatchTransactionsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateBatchTransactionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBatchTransactionsResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CreateBatchTransactionsResponseMultiError, or nil if none found.
func (m *CreateBatchTransactionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBatchTransactionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	// no validation rules for Code

	if len(errors) > 0 {
		return CreateBatchTransactionsResponseMultiError(errors)
	}

	return nil
}

// CreateBatchTransactionsResponseMultiError is an error wrapping multiple
// validation errors returned by CreateBatchTransactionsResponse.ValidateAll()
// if the designated constraints aren't met.
type CreateBatchTransactionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBatchTransactionsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBatchTransactionsResponseMultiError) AllErrors() []error { return m }

// CreateBatchTransactionsResponseValidationError is the validation error
// returned by CreateBatchTransactionsResponse.Validate if the designated
// constraints aren't met.
type CreateBatchTransactionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBatchTransactionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBatchTransactionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBatchTransactionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBatchTransactionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBatchTransactionsResponseValidationError) ErrorName() string {
	return "CreateBatchTransactionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateBatchTransactionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBatchTransactionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBatchTransactionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBatchTransactionsResponseValidationError{}

// Validate checks the field values on GetTransactionsCountRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTransactionsCountRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTransactionsCountRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTransactionsCountRequestMultiError, or nil if none found.
func (m *GetTransactionsCountRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTransactionsCountRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetRequestId()) < 1 {
		err := GetTransactionsCountRequestValidationError{
			field:  "RequestId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetRequestId()); err != nil {
		err = GetTransactionsCountRequestValidationError{
			field:  "RequestId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetTransactionsCountRequestMultiError(errors)
	}

	return nil
}

func (m *GetTransactionsCountRequest) _validateUuid(uuid string) error {
	if matched := _transaction_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetTransactionsCountRequestMultiError is an error wrapping multiple
// validation errors returned by GetTransactionsCountRequest.ValidateAll() if
// the designated constraints aren't met.
type GetTransactionsCountRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTransactionsCountRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTransactionsCountRequestMultiError) AllErrors() []error { return m }

// GetTransactionsCountRequestValidationError is the validation error returned
// by GetTransactionsCountRequest.Validate if the designated constraints
// aren't met.
type GetTransactionsCountRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTransactionsCountRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTransactionsCountRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTransactionsCountRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTransactionsCountRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTransactionsCountRequestValidationError) ErrorName() string {
	return "GetTransactionsCountRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetTransactionsCountRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTransactionsCountRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTransactionsCountRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTransactionsCountRequestValidationError{}

// Validate checks the field values on GetTransactionsCountResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetTransactionsCountResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTransactionsCountResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetTransactionsCountResponseMultiError, or nil if none found.
func (m *GetTransactionsCountResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTransactionsCountResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Count

	// no validation rules for Code

	if len(errors) > 0 {
		return GetTransactionsCountResponseMultiError(errors)
	}

	return nil
}

// GetTransactionsCountResponseMultiError is an error wrapping multiple
// validation errors returned by GetTransactionsCountResponse.ValidateAll() if
// the designated constraints aren't met.
type GetTransactionsCountResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTransactionsCountResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTransactionsCountResponseMultiError) AllErrors() []error { return m }

// GetTransactionsCountResponseValidationError is the validation error returned
// by GetTransactionsCountResponse.Validate if the designated constraints
// aren't met.
type GetTransactionsCountResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTransactionsCountResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTransactionsCountResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTransactionsCountResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTransactionsCountResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTransactionsCountResponseValidationError) ErrorName() string {
	return "GetTransactionsCountResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetTransactionsCountResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTransactionsCountResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTransactionsCountResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTransactionsCountResponseValidationError{}

// Validate checks the field values on GetTransactionsByTypeAndRequestIDRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *GetTransactionsByTypeAndRequestIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// GetTransactionsByTypeAndRequestIDRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// GetTransactionsByTypeAndRequestIDRequestMultiError, or nil if none found.
func (m *GetTransactionsByTypeAndRequestIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTransactionsByTypeAndRequestIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetRequestId()) < 1 {
		err := GetTransactionsByTypeAndRequestIDRequestValidationError{
			field:  "RequestId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetRequestId()); err != nil {
		err = GetTransactionsByTypeAndRequestIDRequestValidationError{
			field:  "RequestId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetType()) < 1 {
		err := GetTransactionsByTypeAndRequestIDRequestValidationError{
			field:  "Type",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetTransactionsByTypeAndRequestIDRequestMultiError(errors)
	}

	return nil
}

func (m *GetTransactionsByTypeAndRequestIDRequest) _validateUuid(uuid string) error {
	if matched := _transaction_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetTransactionsByTypeAndRequestIDRequestMultiError is an error wrapping
// multiple validation errors returned by
// GetTransactionsByTypeAndRequestIDRequest.ValidateAll() if the designated
// constraints aren't met.
type GetTransactionsByTypeAndRequestIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTransactionsByTypeAndRequestIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTransactionsByTypeAndRequestIDRequestMultiError) AllErrors() []error { return m }

// GetTransactionsByTypeAndRequestIDRequestValidationError is the validation
// error returned by GetTransactionsByTypeAndRequestIDRequest.Validate if the
// designated constraints aren't met.
type GetTransactionsByTypeAndRequestIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTransactionsByTypeAndRequestIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTransactionsByTypeAndRequestIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTransactionsByTypeAndRequestIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTransactionsByTypeAndRequestIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTransactionsByTypeAndRequestIDRequestValidationError) ErrorName() string {
	return "GetTransactionsByTypeAndRequestIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetTransactionsByTypeAndRequestIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTransactionsByTypeAndRequestIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTransactionsByTypeAndRequestIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTransactionsByTypeAndRequestIDRequestValidationError{}

// Validate checks the field values on
// GetTransactionsByTypeAndRequestIDResponse with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetTransactionsByTypeAndRequestIDResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// GetTransactionsByTypeAndRequestIDResponse with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// GetTransactionsByTypeAndRequestIDResponseMultiError, or nil if none found.
func (m *GetTransactionsByTypeAndRequestIDResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTransactionsByTypeAndRequestIDResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTransactions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetTransactionsByTypeAndRequestIDResponseValidationError{
						field:  fmt.Sprintf("Transactions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetTransactionsByTypeAndRequestIDResponseValidationError{
						field:  fmt.Sprintf("Transactions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetTransactionsByTypeAndRequestIDResponseValidationError{
					field:  fmt.Sprintf("Transactions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Code

	if len(errors) > 0 {
		return GetTransactionsByTypeAndRequestIDResponseMultiError(errors)
	}

	return nil
}

// GetTransactionsByTypeAndRequestIDResponseMultiError is an error wrapping
// multiple validation errors returned by
// GetTransactionsByTypeAndRequestIDResponse.ValidateAll() if the designated
// constraints aren't met.
type GetTransactionsByTypeAndRequestIDResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTransactionsByTypeAndRequestIDResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTransactionsByTypeAndRequestIDResponseMultiError) AllErrors() []error { return m }

// GetTransactionsByTypeAndRequestIDResponseValidationError is the validation
// error returned by GetTransactionsByTypeAndRequestIDResponse.Validate if the
// designated constraints aren't met.
type GetTransactionsByTypeAndRequestIDResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTransactionsByTypeAndRequestIDResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTransactionsByTypeAndRequestIDResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTransactionsByTypeAndRequestIDResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTransactionsByTypeAndRequestIDResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTransactionsByTypeAndRequestIDResponseValidationError) ErrorName() string {
	return "GetTransactionsByTypeAndRequestIDResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetTransactionsByTypeAndRequestIDResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTransactionsByTypeAndRequestIDResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTransactionsByTypeAndRequestIDResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTransactionsByTypeAndRequestIDResponseValidationError{}

// Validate checks the field values on
// GetTransactionsByMethodAndRequestIDRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetTransactionsByMethodAndRequestIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// GetTransactionsByMethodAndRequestIDRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// GetTransactionsByMethodAndRequestIDRequestMultiError, or nil if none found.
func (m *GetTransactionsByMethodAndRequestIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTransactionsByMethodAndRequestIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetRequestId()) < 1 {
		err := GetTransactionsByMethodAndRequestIDRequestValidationError{
			field:  "RequestId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetRequestId()); err != nil {
		err = GetTransactionsByMethodAndRequestIDRequestValidationError{
			field:  "RequestId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetMethod()) < 1 {
		err := GetTransactionsByMethodAndRequestIDRequestValidationError{
			field:  "Method",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetTransactionsByMethodAndRequestIDRequestMultiError(errors)
	}

	return nil
}

func (m *GetTransactionsByMethodAndRequestIDRequest) _validateUuid(uuid string) error {
	if matched := _transaction_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetTransactionsByMethodAndRequestIDRequestMultiError is an error wrapping
// multiple validation errors returned by
// GetTransactionsByMethodAndRequestIDRequest.ValidateAll() if the designated
// constraints aren't met.
type GetTransactionsByMethodAndRequestIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTransactionsByMethodAndRequestIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTransactionsByMethodAndRequestIDRequestMultiError) AllErrors() []error { return m }

// GetTransactionsByMethodAndRequestIDRequestValidationError is the validation
// error returned by GetTransactionsByMethodAndRequestIDRequest.Validate if
// the designated constraints aren't met.
type GetTransactionsByMethodAndRequestIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTransactionsByMethodAndRequestIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTransactionsByMethodAndRequestIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTransactionsByMethodAndRequestIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTransactionsByMethodAndRequestIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTransactionsByMethodAndRequestIDRequestValidationError) ErrorName() string {
	return "GetTransactionsByMethodAndRequestIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetTransactionsByMethodAndRequestIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTransactionsByMethodAndRequestIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTransactionsByMethodAndRequestIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTransactionsByMethodAndRequestIDRequestValidationError{}

// Validate checks the field values on
// GetTransactionsByMethodAndRequestIDResponse with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetTransactionsByMethodAndRequestIDResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// GetTransactionsByMethodAndRequestIDResponse with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// GetTransactionsByMethodAndRequestIDResponseMultiError, or nil if none found.
func (m *GetTransactionsByMethodAndRequestIDResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTransactionsByMethodAndRequestIDResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTransactions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetTransactionsByMethodAndRequestIDResponseValidationError{
						field:  fmt.Sprintf("Transactions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetTransactionsByMethodAndRequestIDResponseValidationError{
						field:  fmt.Sprintf("Transactions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetTransactionsByMethodAndRequestIDResponseValidationError{
					field:  fmt.Sprintf("Transactions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Code

	if len(errors) > 0 {
		return GetTransactionsByMethodAndRequestIDResponseMultiError(errors)
	}

	return nil
}

// GetTransactionsByMethodAndRequestIDResponseMultiError is an error wrapping
// multiple validation errors returned by
// GetTransactionsByMethodAndRequestIDResponse.ValidateAll() if the designated
// constraints aren't met.
type GetTransactionsByMethodAndRequestIDResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTransactionsByMethodAndRequestIDResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTransactionsByMethodAndRequestIDResponseMultiError) AllErrors() []error { return m }

// GetTransactionsByMethodAndRequestIDResponseValidationError is the validation
// error returned by GetTransactionsByMethodAndRequestIDResponse.Validate if
// the designated constraints aren't met.
type GetTransactionsByMethodAndRequestIDResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTransactionsByMethodAndRequestIDResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTransactionsByMethodAndRequestIDResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTransactionsByMethodAndRequestIDResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTransactionsByMethodAndRequestIDResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTransactionsByMethodAndRequestIDResponseValidationError) ErrorName() string {
	return "GetTransactionsByMethodAndRequestIDResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetTransactionsByMethodAndRequestIDResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTransactionsByMethodAndRequestIDResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTransactionsByMethodAndRequestIDResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTransactionsByMethodAndRequestIDResponseValidationError{}

// Validate checks the field values on GetTransactionsByRequestIDRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetTransactionsByRequestIDRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTransactionsByRequestIDRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// GetTransactionsByRequestIDRequestMultiError, or nil if none found.
func (m *GetTransactionsByRequestIDRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTransactionsByRequestIDRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetRequestId()) < 1 {
		err := GetTransactionsByRequestIDRequestValidationError{
			field:  "RequestId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetRequestId()); err != nil {
		err = GetTransactionsByRequestIDRequestValidationError{
			field:  "RequestId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetTransactionsByRequestIDRequestMultiError(errors)
	}

	return nil
}

func (m *GetTransactionsByRequestIDRequest) _validateUuid(uuid string) error {
	if matched := _transaction_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetTransactionsByRequestIDRequestMultiError is an error wrapping multiple
// validation errors returned by
// GetTransactionsByRequestIDRequest.ValidateAll() if the designated
// constraints aren't met.
type GetTransactionsByRequestIDRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTransactionsByRequestIDRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTransactionsByRequestIDRequestMultiError) AllErrors() []error { return m }

// GetTransactionsByRequestIDRequestValidationError is the validation error
// returned by GetTransactionsByRequestIDRequest.Validate if the designated
// constraints aren't met.
type GetTransactionsByRequestIDRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTransactionsByRequestIDRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTransactionsByRequestIDRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTransactionsByRequestIDRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTransactionsByRequestIDRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTransactionsByRequestIDRequestValidationError) ErrorName() string {
	return "GetTransactionsByRequestIDRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetTransactionsByRequestIDRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTransactionsByRequestIDRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTransactionsByRequestIDRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTransactionsByRequestIDRequestValidationError{}

// Validate checks the field values on GetTransactionsByRequestIDResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetTransactionsByRequestIDResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetTransactionsByRequestIDResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// GetTransactionsByRequestIDResponseMultiError, or nil if none found.
func (m *GetTransactionsByRequestIDResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetTransactionsByRequestIDResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTransactions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetTransactionsByRequestIDResponseValidationError{
						field:  fmt.Sprintf("Transactions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetTransactionsByRequestIDResponseValidationError{
						field:  fmt.Sprintf("Transactions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetTransactionsByRequestIDResponseValidationError{
					field:  fmt.Sprintf("Transactions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Code

	if len(errors) > 0 {
		return GetTransactionsByRequestIDResponseMultiError(errors)
	}

	return nil
}

// GetTransactionsByRequestIDResponseMultiError is an error wrapping multiple
// validation errors returned by
// GetTransactionsByRequestIDResponse.ValidateAll() if the designated
// constraints aren't met.
type GetTransactionsByRequestIDResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetTransactionsByRequestIDResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetTransactionsByRequestIDResponseMultiError) AllErrors() []error { return m }

// GetTransactionsByRequestIDResponseValidationError is the validation error
// returned by GetTransactionsByRequestIDResponse.Validate if the designated
// constraints aren't met.
type GetTransactionsByRequestIDResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetTransactionsByRequestIDResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetTransactionsByRequestIDResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetTransactionsByRequestIDResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetTransactionsByRequestIDResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetTransactionsByRequestIDResponseValidationError) ErrorName() string {
	return "GetTransactionsByRequestIDResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetTransactionsByRequestIDResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetTransactionsByRequestIDResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetTransactionsByRequestIDResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetTransactionsByRequestIDResponseValidationError{}
